// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, RuntimeFailure, EventCapability, EventPublishResult, NativeEventEndpoint, NativeEventHandle};

pub const CAPABILITY_ID: &str = "lenso.story.events@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const EVENTS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const EVENTS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const RECORD_OPERATION: &str = "record";

pub type Int64 = String;
pub type Uint64 = String;
pub type Bytes = String;
pub type Timestamp = String;
pub type Duration = String;
pub type OptionalValue<T> = Option<Option<T>>;

#[allow(dead_code)]
fn deserialize_required<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <T as serde::Deserialize>::deserialize(deserializer)
}

#[allow(dead_code, clippy::option_option)]
fn deserialize_optional_value<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    Ok(Some(<Option<T> as serde::Deserialize>::deserialize(deserializer)?))
}

#[allow(dead_code)]
fn validate_portable_json_value(value: &serde_json::Value) -> Result<(), String> {
    match value {
        serde_json::Value::Number(number) => {
            let safe = number.as_i64().is_some_and(|value| (-9_007_199_254_740_991..=9_007_199_254_740_991).contains(&value))
                || number.as_u64().is_some_and(|value| value <= 9_007_199_254_740_991)
                || (number.is_f64() && number.as_f64().is_some_and(|value| value.is_finite() && (value.abs() <= 9_007_199_254_740_991.0 || value.fract() != 0.0)));
            if !safe {
                return Err("wire JSON contains an unsafe number".to_owned());
            }
        }
        serde_json::Value::Array(values) => {
            for value in values {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Object(values) => {
            for value in values.values() {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Null | serde_json::Value::Bool(_) | serde_json::Value::String(_) => {}
    }
    Ok(())
}

#[allow(dead_code)]
fn portable_json_error(detail: String) -> serde_json::Error {
    serde_json::Error::io(std::io::Error::new(std::io::ErrorKind::InvalidData, detail))
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UnknownDomainError {
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    #[serde(default, flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RecordRequest {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "deserialize_required")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    #[serde(deserialize_with = "deserialize_required")]
    pub event_type: String,
    #[serde(rename = "event_version")]
    #[serde(deserialize_with = "deserialize_required")]
    pub event_version: i64,
    #[serde(rename = "facts")]
    #[serde(deserialize_with = "deserialize_required")]
    pub facts: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "subject_id")]
    #[serde(deserialize_with = "deserialize_required")]
    pub subject_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RecordError {
    ConflictingEventId,
    InvalidEvent,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Events;
impl EventCapability for Events {
    type Event = RecordRequest;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for RecordError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ConflictingEventId => serializer.serialize_str("conflicting_event_id"),
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RecordError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflicting_event_id" => Ok(Self::ConflictingEventId),
                "invalid_event" => Ok(Self::InvalidEvent),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_record_request(value: &RecordRequest) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_record_request(wire: &str) -> Result<RecordRequest, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_record_response(value: &()) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_record_response(wire: &str) -> Result<(), serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_record_error(value: &RecordError) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_record_error(wire: &str) -> Result<RecordError, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }

pub fn encode_record_event(value: &RecordRequest) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_record_event(wire: &str) -> Result<RecordRequest, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }

pub trait EventsProvider: fmt::Debug + 'static {
    fn record(&self, context: InvocationContext, event: RecordRequest);
}

#[derive(Debug)]
pub struct EventsEndpoint<P> { provider: Rc<P> }
impl<P: EventsProvider> EventsEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: EventsProvider> NativeEventEndpoint for EventsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        RECORD_OPERATION,
    ] }
    fn publish(&self, operation: &str, event: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        match operation {
            RECORD_OPERATION => {
                let Ok(event) = event.downcast::<RecordRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    provider.record(context, *event);
                    Ok(())
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct EventsClient {
    record: NativeEventHandle<Events>,
}
impl EventsClient {
    pub fn new(handle: NativeEventHandle<Events>) -> Self {
        Self { record: handle }
    }

    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            record: dependencies.many_event::<Events>()?,
        })
    }

    pub async fn record(&self, event: RecordRequest) -> Vec<EventPublishResult> {
        self.record.publish(RECORD_OPERATION, event).await
    }

    pub async fn record_with_context(&self, context: InvocationContext, event: RecordRequest) -> Vec<EventPublishResult> {
        self.record.publish_with_context(RECORD_OPERATION, context, event).await
    }
}
