//! Offline admission of exact Environment/Execution/named-resource combinations.
//! Uses existing Host authority and Root resolution; never executes source or tools.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, bail, ensure};
use clap::Args;
use lenso_app_plan::{
    CapabilityOperationKind, ExecutionTargetCapabilities, ExecutionTargetCapability,
    authoring::ResolvedApp,
};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

mod source;

/// Build calls this before any compiler, extractor, package hook or tool probe.
/// Existing Apps with no exact-support declaration retain their simple path.
pub(super) fn before_build(
    root: &Path,
    target: &str,
    from: Option<&Path>,
    facilities: Option<&Path>,
) -> anyhow::Result<()> {
    if from.is_some() || facilities.is_some() || source::has_declarations(root)? {
        inspect(root, target, from, facilities).context(
            "target preflight rejected before compilation; no Cargo/Bun/Wasm build started",
        )?;
    }
    Ok(())
}

#[derive(Clone, Debug, Args)]
pub struct CheckArgs {
    /// App source or built App root. Defaults to the current directory.
    #[arg(long)]
    pub root: Option<PathBuf>,
    /// Check Native or the static linked-Rust Workers target without compiling.
    #[arg(long, value_parser = ["native", "workers"])]
    pub target: Option<String>,
    /// Existing generated Host authority for a source App; source identities must match.
    #[arg(long, requires = "target")]
    pub from: Option<PathBuf>,
    /// Host-authorized per-Instance named resources (lenso.host-facilities.v1).
    #[arg(long, requires = "target")]
    pub host_facilities: Option<PathBuf>,
    /// Emit a stable JSON report.
    #[arg(long)]
    pub json: bool,
}

/// One declaration is one whole tuple. Separate axis lists are not accepted.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
struct Support {
    environment: String,
    execution: String,
    #[serde(default)]
    resources: BTreeMap<String, String>,
}

#[derive(Default, Deserialize)]
#[serde(deny_unknown_fields)]
struct Declaration {
    #[serde(default)]
    combinations: Vec<Support>,
    /// External receipts remain references, never proof generated by this check.
    #[serde(default)]
    evidence: Vec<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Grants {
    schema: String,
    instances: BTreeMap<String, BTreeMap<String, Value>>,
}

pub fn run(args: CheckArgs) -> anyhow::Result<()> {
    let root = crate::plugins::project_root(args.root)?;
    let Some(target) = args.target else {
        let report = super::inspect_app_check(&root)?;
        if args.json {
            println!("{}", serde_json::to_string_pretty(&report)?);
        } else {
            println!(
                "App is valid: {} Plugin Instance(s), {} Capability binding(s).",
                report.plugin_instances, report.capability_bindings
            );
        }
        return Ok(());
    };
    let report = inspect(
        &root,
        &target,
        args.from.as_deref(),
        args.host_facilities.as_deref(),
    )?;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&report)?);
    } else {
        println!(
            "App target check passed for {target}: {} Instance(s); qualification not assessed; no build started.",
            report["instances"].as_array().unwrap().len()
        );
    }
    Ok(())
}

pub(super) fn inspect(
    root: &Path,
    target: &str,
    from: Option<&Path>,
    facilities: Option<&Path>,
) -> anyhow::Result<Value> {
    ensure!(
        matches!(target, "native" | "workers"),
        "unsupported check target `{target}`; available: native, workers"
    );
    let (resolved, declarations) = source::resolve(root, from)?;
    let grants = facilities
        .map(read_grants)
        .transpose()?
        .unwrap_or_else(|| Grants {
            schema: "lenso.host-facilities.v1".into(),
            instances: BTreeMap::new(),
        });
    let reports = admit(&resolved, target, &declarations, &grants)?;
    let facility_report = super::facility_inspection::report(
        from.unwrap_or(root),
        resolved.plan(),
        target,
        facilities,
    )?;
    if let Some(rejected) = facility_report["bindings"].as_array().and_then(|bindings| {
        bindings
            .iter()
            .find(|binding| binding["status"] == "rejected")
    }) {
        bail!(
            "instance `{}` resource `{}`: required source-owned {target} binding factory; available: {}",
            rejected["instance_key"].as_str().unwrap_or("unknown"),
            rejected["slot"].as_str().unwrap_or("unknown"),
            rejected["reason"]
        );
    }
    if target == "workers" {
        super::local_workflow::admit_linked_workers(resolved.plan()).context(
            "required static linked Workers target restrictions; available: selected App graph",
        )?;
    }
    Ok(
        json!({"schema_version":1,"kind":"lenso.app-target-check","status":"passed","target":target,
        "plugin_instances":resolved.instances().len(),"capability_bindings":resolved.plan().capability_bindings().len(),
        "instances":reports,"host_facilities":facility_report,"qualification":"not_assessed","resource_readiness":"not_run",
        "build_started":false,"secret_values_read":false}),
    )
}

fn read_grants(path: &Path) -> anyhow::Result<Grants> {
    let grants: Grants = serde_json::from_value(source::read_json(path)?)?;
    ensure!(
        grants.schema == "lenso.host-facilities.v1",
        "unsupported Host facility schema"
    );
    ensure!(
        grants.instances.len() <= 256,
        "Host facility Instance limit exceeded"
    );
    Ok(grants)
}

fn admit(
    resolved: &ResolvedApp,
    target: &str,
    declarations: &BTreeMap<String, Declaration>,
    grants: &Grants,
) -> anyhow::Result<Vec<Value>> {
    let plan = resolved.plan();
    let mut reports = Vec::new();
    for key in grants.instances.keys() {
        ensure!(
            plan.plugin_instance(key).is_some(),
            "instance `{key}`: required selected Instance; available: no matching Instance"
        );
    }
    for instance in resolved.instances() {
        let id = instance.id().to_string();
        let selected = plan
            .plugin_instance(instance.plan_key())
            .context("resolved Instance missing from Plan")?;
        let execution = selected.execution_class().as_str();
        let available = target_features(target, execution, selected.runtime_profile())
            .with_context(|| {
                format!(
                    "instance `{id}`: required execution `{execution}`; available target `{target}`"
                )
            })?;
        let mut required = selected.required_target_capabilities().to_vec();
        for endpoint in selected.provided_capabilities().iter().chain(
            plan.capability_bindings()
                .iter()
                .filter(|b| b.consumer_instance() == instance.plan_key())
                .filter_map(|b| {
                    plan.plugin_instance(b.provider_instance()).and_then(|p| {
                        p.provided_capabilities().iter().find(|e| {
                            e.capability_id() == b.capability_id()
                                && e.descriptor_version() == b.descriptor_version()
                        })
                    })
                }),
        ) {
            for operation in endpoint.operations() {
                required.push(match endpoint.operation_kind(operation) {
                    Some(CapabilityOperationKind::Request) => ExecutionTargetCapability::Request,
                    Some(CapabilityOperationKind::Stream) => ExecutionTargetCapability::Stream,
                    Some(CapabilityOperationKind::Event) => ExecutionTargetCapability::Event,
                    None => bail!("instance `{id}`: required declared operation `{operation}`; available: none"),
                });
            }
        }
        let missing = available.missing(required);
        ensure!(
            missing.is_empty(),
            "instance `{id}`: required target features {missing:?}; available: {:?}",
            available.features()
        );
        if target == "workers" {
            ensure!(
                selected.restart_policy() == lenso_app_plan::RestartPolicy::never(),
                "instance `{id}`: required restart supervision; available: static Workers without restart supervision"
            );
        }
        let resources = resource_types(&id, grants.instances.get(instance.plan_key()), target)?;
        let wanted = Support {
            environment: target.into(),
            execution: execution.into(),
            resources,
        };
        let default_environment =
            if target == "workers" && instance.id().plugin_id() == "lenso.web-ingress" {
                "workers"
            } else {
                "native"
            };
        let default = Declaration {
            combinations: vec![Support {
                environment: default_environment.into(),
                execution: execution.into(),
                resources: BTreeMap::new(),
            }],
            evidence: vec![],
        };
        let declaration = declarations
            .get(instance.id().plugin_id())
            .unwrap_or(&default);
        validate_declaration(declaration)?;
        ensure!(
            declaration.combinations.contains(&wanted),
            "instance `{id}`: required exact support {}; available declared combinations: {}",
            serde_json::to_string(&wanted)?,
            serde_json::to_string(&declaration.combinations)?
        );
        reports.push(
            json!({"instance":id,"combination":wanted,"support":"declared",
            "qualification":"not_assessed","evidence_references":declaration.evidence}),
        );
    }
    Ok(reports)
}

fn validate_declaration(declaration: &Declaration) -> anyhow::Result<()> {
    ensure!(
        !declaration.combinations.is_empty() && declaration.combinations.len() <= 64,
        "support needs 1..64 exact combinations"
    );
    for (index, tuple) in declaration.combinations.iter().enumerate() {
        ensure!(
            matches!(tuple.environment.as_str(), "native" | "workers"),
            "invalid support environment"
        );
        ensure!(
            !tuple.execution.is_empty() && tuple.resources.len() <= 16,
            "invalid support execution/resources"
        );
        ensure!(
            !declaration.combinations[..index].contains(tuple),
            "duplicate exact support combination"
        );
        for (name, implementation) in &tuple.resources {
            ensure!(
                valid_name(name) && valid_name(implementation),
                "invalid named support resource"
            );
        }
    }
    ensure!(
        declaration.evidence.len() <= 64
            && declaration
                .evidence
                .iter()
                .all(|reference| !reference.is_empty() && reference.len() <= 1024),
        "invalid evidence references"
    );
    Ok(())
}

fn resource_types(
    id: &str,
    slots: Option<&BTreeMap<String, Value>>,
    target: &str,
) -> anyhow::Result<BTreeMap<String, String>> {
    let mut types = BTreeMap::new();
    for (slot, grant) in slots.into_iter().flatten() {
        ensure!(valid_name(slot), "instance `{id}`: invalid resource name");
        let object = grant
            .as_object()
            .context("Host resource must be an object")?;
        ensure!(
            object.len() == 2
                && object.contains_key("configuration")
                && object.contains_key("binding"),
            "instance `{id}` resource `{slot}`: required configuration and binding references; available: invalid grant"
        );
        let implementation = grant["configuration"]["implementation"]
            .as_str()
            .with_context(|| {
                format!(
                    "instance `{id}` resource `{slot}`: required implementation; available: none"
                )
            })?;
        ensure!(
            valid_name(implementation),
            "invalid resource implementation"
        );
        if target == "workers" {
            ensure!(
                grant["binding"].as_str().is_some_and(valid_binding),
                "instance `{id}` resource `{slot}`: required Workers binding reference; available: none/invalid"
            );
        } else {
            ensure!(
                grant["binding"].is_null()
                    && grant["configuration"]["reference"]
                        .as_str()
                        .is_some_and(valid_name),
                "instance `{id}` resource `{slot}`: required Native resource reference; available: none/invalid"
            );
        }
        types.insert(slot.clone(), implementation.into());
    }
    Ok(types)
}

fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 128
        && name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'-' | b'_' | b'@'))
}

fn valid_binding(name: &str) -> bool {
    valid_name(name)
        && name
            .bytes()
            .next()
            .is_some_and(|b| b.is_ascii_alphabetic() || b == b'_')
        && name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
}

fn target_features(
    target: &str,
    execution: &str,
    profile: &str,
) -> anyhow::Result<ExecutionTargetCapabilities> {
    use ExecutionTargetCapability as F;
    if target == "workers" {
        ensure!(
            execution == "lenso.native-rust@1"
                && matches!(
                    profile,
                    "lenso.native-rust@1" | "lenso.native-authoring@1" | "lenso.native-authoring@2"
                ),
            "available execution: static linked Rust Workers (lenso.native-rust@1)"
        );
        // Matches the existing linked Workers admission; no Event/WebSocket/restart.
        return Ok(ExecutionTargetCapabilities::new([
            F::Request,
            F::Stream,
            F::Workers,
            F::HostImports,
        ]));
    }
    let features = match (execution, profile) {
        (
            "lenso.native-rust@1",
            "lenso.native-rust@1" | "lenso.native-authoring@1" | "lenso.native-authoring@2",
        ) => vec![F::Request, F::Stream, F::Event, F::HostImports],
        ("lenso.bun-process@1", lenso_bun_adapter::BUN_AUTHORING_RUNTIME_PROFILE) => {
            profile_features(&crate::target_profile::bun_admission()?.capability_profile())
        }
        (
            "lenso.process@1",
            lenso_process_adapter::RUNTIME_PROFILE_V1 | lenso_process_adapter::RUNTIME_PROFILE_V2,
        ) => vec![F::Request, F::NativeProcess],
        ("lenso.wasm-component@1", lenso_wasm_component_adapter::RUNTIME_PROFILE) => {
            profile_features(
                &crate::target_profile::request_wasm_component_admission(
                    lenso_app_plan::ExecutionClassId::new(execution),
                    profile,
                )
                .capability_profile(),
            )
        }
        _ => bail!(
            "available execution: Native linked Rust, Bun, Process or Wasm Component with an admitted runtime profile"
        ),
    };
    Ok(ExecutionTargetCapabilities::new(features))
}

fn profile_features(
    profile: &lenso_plugin_bundle::ExecutionTargetCapabilityProfile,
) -> Vec<ExecutionTargetCapability> {
    ExecutionTargetCapability::ALL
        .into_iter()
        .filter(|feature| profile.supports_named(feature.as_str()))
        .collect()
}

#[cfg(test)]
mod tests;
