/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.notes.jsonc --include-runtime=false --env-interface=NotesEnv worker-notes.d.ts` (hash: 3d230b829a31dc1b669a709fccee08ee)
interface __BaseEnv_NotesEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/notes");
	}
	interface Env extends __BaseEnv_NotesEnv {}
}
interface NotesEnv extends __BaseEnv_NotesEnv {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}