import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineEnginePlugin, type EngineSnapshot } from "./engine-authoring";
import { describeOperation, redactOperationDescription } from "./operations";
import { environmentSecrets, redact, stableJson } from "./diagnostics";
import type { Discovery, PluginManifest } from "./application";

export const defaultEngineOwner = "lenso/defaults";
const header = "// Generated by @lenso/engine; run lenso generate after changing assembly.\n";
/** Official stages register through exactly the same API as application plugins. */
export function defaultEnginePlugins(readApp: (snapshot: EngineSnapshot) => Promise<Discovery>) {
  return [
    defineEnginePlugin({
      name: defaultEngineOwner,
      source: { file: fileURLToPath(import.meta.url) },
      setup(context) {
        context.convention(async () => ({
          config: "lenso.config.ts",
          ...((await Bun.file(join(context.root, "src/server.ts")).exists())
            ? { entry: "src/server.ts" }
            : {}),
          ...((await Bun.file(join(context.root, "src/router.ts")).exists())
            ? { router: "src/router.ts" }
            : {}),
        }));
        context.generate("manifest", async (snapshot) => {
          const discovery = await readApp(snapshot);
          const manifest = pluginManifest(discovery);
          stableJson(manifest);
          const data = {
            schemaVersion: 1,
            generatedBy: "@lenso/engine",
            source: snapshot.convention.config,
            plugins: redact(manifest, environmentSecrets()),
            operations: (discovery.app.operations ?? []).map((operation) =>
              redactOperationDescription(describeOperation(operation, snapshot.convention.config)),
            ),
          };
          return [{ path: "manifest.json", content: `${stableJson(data, 2)}\n` }];
        });
        context.generate("server", (snapshot) => [
          {
            path: "server.ts",
            content: `${header}export { default as app } from ${JSON.stringify(snapshot.importPath("server.ts", snapshot.convention.config))};\n`,
          },
        ]);
        context.generate("client", (snapshot) => [
          {
            path: "client.ts",
            content: snapshot.convention.router
              ? `${header}import { createClient as createWebClient } from '@lenso/web/client';\nimport type { AppRouter } from ${JSON.stringify(snapshot.importPath("client.ts", snapshot.convention.router))};\nexport type { AppRouter };\nexport const createClient = (url: string) => createWebClient<AppRouter>(url);\n`
              : `${header}export {};\n`,
          },
        ]);
        context.target("bun", (context) => context.bundle({ entry: context.entry }));
      },
    }),
  ];
}
export function pluginManifest(discovery: Discovery): readonly PluginManifest[] {
  return discovery.ordered.map((plugin) => ({
    id: plugin.id,
    requires: (plugin.requires ?? []).map((dependency) => dependency.id),
    contributions: plugin.contributions ?? [],
  }));
}
