use super::*;
use serde_json::json;

#[test]
fn published_legacy_projection_is_reused_in_consumer_output_with_source_freshness() {
    for source in [
        "registry+https://example.invalid/index",
        "git+https://example.invalid/contracts?rev=locked",
    ] {
        let consumer = tempfile::tempdir().unwrap();
        let dependency = tempfile::tempdir().unwrap();
        descriptor(dependency.path(), "example.external@1");
        let digest = load_descriptor(&dependency.path().join("capability.json"))
            .unwrap()
            .descriptor_digest()
            .to_owned();
        let original = dependency.path().join("src/generated.rs");
        fs::create_dir(original.parent().unwrap()).unwrap();
        let prebuilt = format!(
            "// @generated by lenso-contract-codegen; do not edit.\npub const DESCRIPTOR_DIGEST: &str = \"{digest}\";\n"
        );
        fs::write(&original, &prebuilt).unwrap();
        fs::write(
            dependency.path().join("build.rs"),
            "fn main() { panic!(\"must not execute\"); }",
        )
        .unwrap();
        fs::write(
            consumer.path().join("Cargo.lock"),
            "version = 4\n# materialized locked fixture\n",
        )
        .unwrap();
        let before = lenso_engine::Snapshot::read(dependency.path()).unwrap();
        let package =
            json!({"id":format!("{source}#external@1.0.0"),"source":source,"dependencies":[]});
        let metadata = json!({"workspace_root":consumer.path(),"packages":[{"id":"legacy-sdk","name":"lenso-guest-sdk","version":"0.4.0"}],"resolve":{"nodes":[{"id":package["id"],"deps":[{"pkg":"legacy-sdk"}]}]}});
        let selected = |module: Option<&str>| {
            let mut contracts = BTreeMap::new();
            insert(&mut contracts, dependency.path().into(), json!({"descriptor":"capability.json","projection":"rust-runtime","output":"src/generated.rs"}), Some((package.clone(),metadata.clone()))).unwrap();
            let config = Configuration {
                dependency_projections: vec![Projection {
                    projection: "rust-runtime".into(),
                    output: "client.rs".into(),
                    module: module.map(str::to_owned),
                }],
                ..Configuration::default()
            };
            configure_external(
                consumer.path(),
                &package,
                &config,
                contracts.get_mut(dependency.path()).unwrap(),
            )
            .unwrap();
            contracts
        };
        let contracts = selected(None);
        let output = contracts[dependency.path()]
            .output_root
            .as_ref()
            .unwrap()
            .join("client.rs");
        let evidence = synchronize_selected(consumer.path(), contracts).unwrap();
        assert_eq!(fs::read_to_string(&output).unwrap(), prebuilt);
        assert_eq!(
            evidence[0].files[&original],
            file_digest(&original).unwrap()
        );
        assert_eq!(evidence[0].files[&output], file_digest(&output).unwrap());
        assert_eq!(
            serde_json::to_value(before).unwrap(),
            serde_json::to_value(lenso_engine::Snapshot::read(dependency.path()).unwrap()).unwrap()
        );
        // A different module cannot silently reuse an incompatible prebuilt.
        assert!(
            synchronize_selected(consumer.path(), selected(Some("named")))
                .unwrap_err()
                .to_string()
                .contains("compatible lenso-contract-codegen build-dependency")
        );
        fs::write(&original, prebuilt.replace(&digest, "stale")).unwrap();
        assert!(
            synchronize_selected(consumer.path(), selected(None))
                .unwrap_err()
                .to_string()
                .contains("compatible lenso-contract-codegen build-dependency")
        );
    }
}

#[test]
fn unlocked_dependencies_are_diagnosed_without_resolution_or_borrowing_parent_lock() {
    let parent = tempfile::tempdir().unwrap();
    fs::write(parent.path().join("Cargo.lock"), "unrelated parent lock").unwrap();
    let root = parent.path().join("fresh");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(root.join("src/lib.rs"), "").unwrap();
    let manifest = root.join("Cargo.toml");
    fs::write(&manifest, "[package]\nname='fresh'\nversion='0.1.0'\nedition='2024'\n[workspace]\n[dependencies]\nlenso-unprepared-dependency-fixture='=99.0.0'\n").unwrap();
    let before = lenso_engine::Snapshot::read(parent.path()).unwrap();
    let error = cargo_metadata(&manifest).unwrap_err().to_string();
    assert!(
        error.contains("Cargo dependencies are not prepared"),
        "{error}"
    );
    assert!(error.contains("cargo generate-lockfile --manifest-path"));
    assert!(error.contains("--no-install"));
    assert!(!root.join("Cargo.lock").exists());
    assert_eq!(
        serde_json::to_value(before).unwrap(),
        serde_json::to_value(lenso_engine::Snapshot::read(parent.path()).unwrap()).unwrap()
    );
}

#[test]
fn dependency_free_local_contract_needs_no_lock_and_discovery_does_not_create_one() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    fs::remove_file(root.join("package.json")).unwrap();
    fs::create_dir(root.join("src")).unwrap();
    fs::write(root.join("src/lib.rs"), "").unwrap();
    fs::write(root.join("Cargo.toml"), "[package]\nname='text-contract'\nversion='1.0.0'\nedition='2024'\n[workspace]\n[package.metadata.lenso.contract]\ndescriptor='capability.json'\nprojection='typescript'\noutput='generated/text.ts'\n").unwrap();
    synchronize(temp.path(), &[]).unwrap();
    assert!(root.join("generated/text.ts").exists());
    assert!(!root.join("Cargo.lock").exists());
}

#[test]
fn local_legacy_guest_reuses_unchanged_projection_without_an_exporter() {
    let consumer = tempfile::tempdir().unwrap();
    let root = consumer.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    let digest = load_descriptor(&root.join("capability.json"))
        .unwrap()
        .descriptor_digest()
        .to_owned();
    let output = root.join("generated/text.rs");
    fs::create_dir_all(output.parent().unwrap()).unwrap();
    let prebuilt = format!(
        "// @generated by lenso-contract-codegen 0.8.2\npub const DESCRIPTOR_DIGEST: &str = \"{digest}\";\n"
    );
    fs::write(&output, &prebuilt).unwrap();
    let modified = fs::metadata(&output).unwrap().modified().unwrap();
    // Locked Cargo metadata describes a direct Guest SDK 0.4 dependency and
    // no codegen build dependency. Synchronization must not execute Cargo.
    let package = json!({"id":"text-contract", "dependencies":[]});
    let metadata = json!({
        "workspace_root":consumer.path(),
        "packages":[{"id":"legacy-sdk","name":"lenso-guest-sdk","version":"0.4.0"}],
        "resolve":{"nodes":[{"id":"text-contract","deps":[{"pkg":"legacy-sdk"}]}]}
    });
    let selected = || {
        let mut contracts = BTreeMap::new();
        insert(
            &mut contracts,
            root.clone(),
            json!({"descriptor":"capability.json","projection":"rust","output":"generated/text.rs"}),
            Some((package.clone(), metadata.clone())),
        )
        .unwrap();
        assert!(targets_legacy_guest(contracts.get(&root).unwrap()));
        contracts
    };
    let evidence = synchronize_selected(consumer.path(), selected()).unwrap();
    assert_eq!(fs::read_to_string(&output).unwrap(), prebuilt);
    assert_eq!(fs::metadata(&output).unwrap().modified().unwrap(), modified);
    assert_eq!(evidence[0].files[&output], file_digest(&output).unwrap());
    // A generated marker alone is insufficient: a stale projection still
    // requires an explicit compatible generator, and is not overwritten.
    let stale = prebuilt.replace(&digest, "stale-contract-digest");
    fs::write(&output, &stale).unwrap();
    let error = synchronize_selected(consumer.path(), selected())
        .unwrap_err()
        .to_string();
    assert!(error.contains("compatible lenso-contract-codegen build-dependency"));
    assert_eq!(fs::read_to_string(&output).unwrap(), stale);
}

#[test]
fn configured_roots_exclusions_and_read_only_freshness_check() {
    let root = tempfile::tempdir().unwrap();
    descriptor(&root.path().join("interfaces/used"), "example.used@1");
    descriptor(&root.path().join("interfaces/ignored"), "example.ignored@1");
    fs::write(
        root.path().join("interfaces/ignored/capability.json"),
        "invalid",
    )
    .unwrap();
    fs::write(
        root.path().join("lenso.toml"),
        "[contracts]\nroots=['interfaces']\nexclude_paths=['interfaces/ignored']\n",
    )
    .unwrap();
    let evidence = synchronize(root.path(), &[]).unwrap();
    assert_eq!(evidence.len(), 1);
    fs::write(
        root.path().join(".lenso/contracts/freshness.json"),
        serde_json::to_vec(&evidence).unwrap(),
    )
    .unwrap();
    check(root.path()).unwrap();
    let output = root.path().join("interfaces/used/generated/text.ts");
    fs::write(&output, "// @generated by lenso-contract-codegen\nstale").unwrap();
    assert!(check(root.path()).is_err());
    assert_eq!(
        fs::read_to_string(output).unwrap(),
        "// @generated by lenso-contract-codegen\nstale"
    );
    assert!(!root.path().join("interfaces/ignored/generated").exists());
}

#[test]
fn declared_processor_policy_checks_actual_projections_without_fake_app_receipt() {
    let root = tempfile::tempdir().unwrap();
    descriptor(&root.path().join("contracts/example"), "example.declared@1");
    let options = lenso_engine_contracts::DiscoveryOptions::default();
    fs::write(
        root.path().join("lenso.contracts.json"),
        serde_json::to_vec(&options).unwrap(),
    )
    .unwrap();
    let (snapshot, selected) = lenso_engine_contracts::discover(root.path(), &options).unwrap();
    lenso_engine_contracts::run(
        snapshot,
        selected,
        root.path(),
        None,
        lenso_engine_contracts::Mode::Generate,
    )
    .unwrap();
    check(root.path()).unwrap();
    assert!(!root.path().join(".lenso/contracts/freshness.json").exists());
    fs::write(root.path().join("contracts/example/generated.ts"), "stale").unwrap();
    assert!(check(root.path()).is_err());
}

#[test]
fn materialized_registry_and_git_snapshots_generate_only_consumer_local_outputs() {
    for source in [
        "registry+https://example.invalid/index",
        "git+https://example.invalid/contracts#0123456789abcdef",
    ] {
        let consumer = tempfile::tempdir().unwrap();
        let dependency = tempfile::tempdir().unwrap();
        descriptor(dependency.path(), "example.external@1");
        fs::write(
            dependency.path().join("contract.rs"),
            "compile_error!(\"dependency source must not execute\");",
        )
        .unwrap();
        fs::write(
            dependency.path().join("build.rs"),
            "fn main() { panic!(\"must not execute\"); }",
        )
        .unwrap();
        fs::write(
            consumer.path().join("Cargo.lock"),
            format!("version = 4\n# locked materialized input: {source}\n"),
        )
        .unwrap();
        let before = lenso_engine::Snapshot::read(dependency.path()).unwrap();
        let declaration: Value =
            serde_json::from_slice(&fs::read(dependency.path().join("package.json")).unwrap())
                .unwrap();
        let package = json!({"id":format!("{source}#example.external@1.0.0"), "source":source, "dependencies":[]});
        let metadata = json!({"workspace_root":consumer.path()});
        let mut contracts = BTreeMap::new();
        insert(
            &mut contracts,
            dependency.path().into(),
            declaration["lenso"]["contract"].clone(),
            Some((package.clone(), metadata)),
        )
        .unwrap();
        let contract = contracts.get_mut(dependency.path()).unwrap();
        contract.declaration.source = Some("contract.rs".into());
        configure_external(
            consumer.path(),
            &package,
            &Configuration::default(),
            contract,
        )
        .unwrap();
        let target = contract
            .output_root
            .clone()
            .unwrap()
            .join("generated/text.ts");
        synchronize_selected(consumer.path(), contracts).unwrap();
        assert!(target.exists());
        assert!(target.starts_with(consumer.path()));
        assert_eq!(
            serde_json::to_value(before).unwrap(),
            serde_json::to_value(lenso_engine::Snapshot::read(dependency.path()).unwrap()).unwrap()
        );
    }
}

fn descriptor(root: &Path, id: &str) {
    fs::create_dir_all(root).unwrap();
    fs::write(root.join("capability.json"), serde_json::to_vec(&json!({
            "id":id,"version":"1.0.0","portable":true,"cross_lane_transfer":false,
            "operations":[{"name":"uppercase","interaction":"request","request_schema":"request.json","response_schema":"response.json","domain_error_schema":"error.json"}]
        })).unwrap()).unwrap();
    for file in ["request.json", "response.json"] {
        fs::write(root.join(file), r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["text"],"properties":{"text":{"type":"string"}}}"#).unwrap();
    }
    fs::write(root.join("error.json"), r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","oneOf":[{"const":"unavailable"}]}"#).unwrap();
    fs::write(root.join("package.json"), serde_json::to_vec(&json!({"name":"text-contract","version":"1.0.0","lenso":{"contract":{"descriptor":"capability.json","projection":"typescript","output":"generated/text.ts"}}})).unwrap()).unwrap();
}

#[test]
fn descriptor_generation_is_stable_and_rejects_incompatible_changes_before_output() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    synchronize(temp.path(), &[]).unwrap();
    let generated = root.join("generated/text.ts");
    let before = fs::read(&generated).unwrap();
    let modified = fs::metadata(&generated).unwrap().modified().unwrap();
    assert!(String::from_utf8_lossy(&before).contains("uppercase"));
    synchronize(temp.path(), &[]).unwrap();
    assert_eq!(
        modified,
        fs::metadata(&generated).unwrap().modified().unwrap()
    );
    let schema = root.join("request.json");
    fs::write(
        &schema,
        fs::read_to_string(&schema)
            .unwrap()
            .replace("string", "integer"),
    )
    .unwrap();
    let error = synchronize(temp.path(), &[]).unwrap_err().to_string();
    assert!(error.contains("explicit compatible version"), "{error}");
    assert_eq!(before, fs::read(&generated).unwrap());
}

#[test]
fn all_contracts_validate_before_generated_files_change() {
    let temp = tempfile::tempdir().unwrap();
    let first = temp.path().join("contracts/a");
    descriptor(&first, "example.a@1");
    let second = temp.path().join("contracts/z");
    descriptor(&second, "example.z@1");
    fs::write(second.join("request.json"), "invalid").unwrap();
    assert!(synchronize(temp.path(), &[]).is_err());
    assert!(!first.join("generated/text.ts").exists());
}

#[test]
fn output_cannot_escape_package_or_overwrite_contract_source() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    let path = root.join("package.json");
    let mut value: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    value["lenso"]["contract"]["output"] = json!("../outside.ts");
    fs::write(&path, serde_json::to_vec(&value).unwrap()).unwrap();
    assert!(
        synchronize(temp.path(), &[])
            .unwrap_err()
            .to_string()
            .contains("inside its package")
    );
    value["lenso"]["contract"]["output"] = json!("capability.json");
    fs::write(&path, serde_json::to_vec(&value).unwrap()).unwrap();
    assert!(
        synchronize(temp.path(), &[])
            .unwrap_err()
            .to_string()
            .contains("authored file")
    );
}

#[test]
fn unrelated_contract_rs_does_not_claim_descriptor_source_authority() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    fs::remove_file(root.join("package.json")).unwrap();
    fs::create_dir(root.join("src")).unwrap();
    fs::write(root.join("src/lib.rs"), "pub mod contract;\n").unwrap();
    fs::write(root.join("src/contract.rs"), "pub fn unrelated() {}\n").unwrap();
    fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"text-contract\"\nversion = \"1.0.0\"\nedition = \"2024\"\n[workspace]\n[package.metadata.lenso.contract]\ndescriptor = \"capability.json\"\nprojection = \"typescript\"\noutput = \"generated/text.ts\"\n",
        )
        .unwrap();

    synchronize(temp.path(), &[]).unwrap();
    assert!(root.join("generated/text.ts").is_file());
    assert_eq!(
        fs::read_to_string(root.join("src/contract.rs")).unwrap(),
        "pub fn unrelated() {}\n"
    );
}

#[test]
#[ignore = "requires Cargo registry access; compiles actual source extraction"]
fn clean_room_source_contract_generates_before_a_stale_library_can_compile() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        r#"
[package]
name = "source-text-contract"
version = "1.0.0"
edition = "2024"
[workspace]
[package.metadata.lenso.contract]
descriptor = "capability.json"
source = "src/contract.rs"
projection = "typescript"
output = "generated/text.ts"
[dependencies]
schemars = "1.2"
lenso-contract-authoring = "=0.1.2"
[build-dependencies]
lenso-contract-codegen = "=0.10.2"
"#,
    )
    .unwrap();
    fs::write(
        root.join("src/lib.rs"),
        "compile_error!(\"stale consumer must not compile during extraction\");",
    )
    .unwrap();
    fs::write(root.join("src/contract.rs"), r#"
use lenso_contract_authoring as lenso;
#[derive(lenso::JsonSchema)]
#[schemars(deny_unknown_fields)]
struct Input { text: String }
#[derive(lenso::DomainError)]
enum Error { Unavailable }
#[lenso::capability(id = "example.text", major = 1, version = "1.0.0", portable = true, cross_lane_transfer = false)]
trait Text {
    async fn uppercase(&self, context: lenso::Ctx<'_>, request: Input) -> Result<Input, Error>;
}
"#).unwrap();
    synchronize(temp.path(), &[]).unwrap();
    assert!(root.join("capability.json").is_file());
    assert!(
        fs::read_to_string(root.join("generated/text.ts"))
            .unwrap()
            .contains("uppercase")
    );
    synchronize(temp.path(), &[]).unwrap();
}
