use super::*;
use serde_json::json;

#[test]
fn configured_roots_exclusions_and_read_only_freshness_check() {
    let root = tempfile::tempdir().unwrap();
    descriptor(&root.path().join("interfaces/used"), "example.used@1");
    descriptor(&root.path().join("interfaces/ignored"), "example.ignored@1");
    fs::write(
        root.path().join("interfaces/ignored/capability.json"),
        "invalid",
    )
    .unwrap();
    fs::write(
        root.path().join("lenso.toml"),
        "[contracts]\nroots=['interfaces']\nexclude_paths=['interfaces/ignored']\n",
    )
    .unwrap();
    let evidence = synchronize(root.path(), &[]).unwrap();
    assert_eq!(evidence.len(), 1);
    fs::write(
        root.path().join(".lenso/contracts/freshness.json"),
        serde_json::to_vec(&evidence).unwrap(),
    )
    .unwrap();
    check(root.path()).unwrap();
    let output = root.path().join("interfaces/used/generated/text.ts");
    fs::write(&output, "// @generated by lenso-contract-codegen\nstale").unwrap();
    assert!(check(root.path()).is_err());
    assert_eq!(
        fs::read_to_string(output).unwrap(),
        "// @generated by lenso-contract-codegen\nstale"
    );
    assert!(!root.path().join("interfaces/ignored/generated").exists());
}

#[test]
fn materialized_registry_and_git_snapshots_generate_only_consumer_local_outputs() {
    for source in [
        "registry+https://example.invalid/index",
        "git+https://example.invalid/contracts#0123456789abcdef",
    ] {
        let consumer = tempfile::tempdir().unwrap();
        let dependency = tempfile::tempdir().unwrap();
        descriptor(dependency.path(), "example.external@1");
        fs::write(
            dependency.path().join("contract.rs"),
            "compile_error!(\"dependency source must not execute\");",
        )
        .unwrap();
        fs::write(
            dependency.path().join("build.rs"),
            "fn main() { panic!(\"must not execute\"); }",
        )
        .unwrap();
        fs::write(
            consumer.path().join("Cargo.lock"),
            format!("version = 4\n# locked materialized input: {source}\n"),
        )
        .unwrap();
        let before = lenso_engine::Snapshot::read(dependency.path()).unwrap();
        let declaration: Value =
            serde_json::from_slice(&fs::read(dependency.path().join("package.json")).unwrap())
                .unwrap();
        let package = json!({"id":format!("{source}#example.external@1.0.0"), "source":source, "dependencies":[]});
        let metadata = json!({"workspace_root":consumer.path()});
        let mut contracts = BTreeMap::new();
        insert(
            &mut contracts,
            dependency.path().into(),
            declaration["lenso"]["contract"].clone(),
            Some((package.clone(), metadata)),
        )
        .unwrap();
        let contract = contracts.get_mut(dependency.path()).unwrap();
        contract.declaration.source = Some("contract.rs".into());
        configure_external(
            consumer.path(),
            &package,
            &Configuration::default(),
            contract,
        )
        .unwrap();
        let target = contract
            .output_root
            .clone()
            .unwrap()
            .join("generated/text.ts");
        synchronize_selected(consumer.path(), contracts).unwrap();
        assert!(target.exists());
        assert!(target.starts_with(consumer.path()));
        assert_eq!(
            serde_json::to_value(before).unwrap(),
            serde_json::to_value(lenso_engine::Snapshot::read(dependency.path()).unwrap()).unwrap()
        );
    }
}

fn descriptor(root: &Path, id: &str) {
    fs::create_dir_all(root).unwrap();
    fs::write(root.join("capability.json"), serde_json::to_vec(&json!({
            "id":id,"version":"1.0.0","portable":true,"cross_lane_transfer":false,
            "operations":[{"name":"uppercase","interaction":"request","request_schema":"request.json","response_schema":"response.json","domain_error_schema":"error.json"}]
        })).unwrap()).unwrap();
    for file in ["request.json", "response.json"] {
        fs::write(root.join(file), r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["text"],"properties":{"text":{"type":"string"}}}"#).unwrap();
    }
    fs::write(root.join("error.json"), r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","oneOf":[{"const":"unavailable"}]}"#).unwrap();
    fs::write(root.join("package.json"), serde_json::to_vec(&json!({"name":"text-contract","version":"1.0.0","lenso":{"contract":{"descriptor":"capability.json","projection":"typescript","output":"generated/text.ts"}}})).unwrap()).unwrap();
}

#[test]
fn descriptor_generation_is_stable_and_rejects_incompatible_changes_before_output() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    synchronize(temp.path(), &[]).unwrap();
    let generated = root.join("generated/text.ts");
    let before = fs::read(&generated).unwrap();
    let modified = fs::metadata(&generated).unwrap().modified().unwrap();
    assert!(String::from_utf8_lossy(&before).contains("uppercase"));
    synchronize(temp.path(), &[]).unwrap();
    assert_eq!(
        modified,
        fs::metadata(&generated).unwrap().modified().unwrap()
    );
    let schema = root.join("request.json");
    fs::write(
        &schema,
        fs::read_to_string(&schema)
            .unwrap()
            .replace("string", "integer"),
    )
    .unwrap();
    let error = synchronize(temp.path(), &[]).unwrap_err().to_string();
    assert!(error.contains("explicit compatible version"), "{error}");
    assert_eq!(before, fs::read(&generated).unwrap());
}

#[test]
fn all_contracts_validate_before_generated_files_change() {
    let temp = tempfile::tempdir().unwrap();
    let first = temp.path().join("contracts/a");
    descriptor(&first, "example.a@1");
    let second = temp.path().join("contracts/z");
    descriptor(&second, "example.z@1");
    fs::write(second.join("request.json"), "invalid").unwrap();
    assert!(synchronize(temp.path(), &[]).is_err());
    assert!(!first.join("generated/text.ts").exists());
}

#[test]
fn output_cannot_escape_package_or_overwrite_contract_source() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    let path = root.join("package.json");
    let mut value: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    value["lenso"]["contract"]["output"] = json!("../outside.ts");
    fs::write(&path, serde_json::to_vec(&value).unwrap()).unwrap();
    assert!(
        synchronize(temp.path(), &[])
            .unwrap_err()
            .to_string()
            .contains("inside its package")
    );
    value["lenso"]["contract"]["output"] = json!("capability.json");
    fs::write(&path, serde_json::to_vec(&value).unwrap()).unwrap();
    assert!(
        synchronize(temp.path(), &[])
            .unwrap_err()
            .to_string()
            .contains("authored file")
    );
}

#[test]
fn unrelated_contract_rs_does_not_claim_descriptor_source_authority() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    descriptor(&root, "example.text@1");
    fs::remove_file(root.join("package.json")).unwrap();
    fs::create_dir(root.join("src")).unwrap();
    fs::write(root.join("src/lib.rs"), "pub mod contract;\n").unwrap();
    fs::write(root.join("src/contract.rs"), "pub fn unrelated() {}\n").unwrap();
    fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"text-contract\"\nversion = \"1.0.0\"\nedition = \"2024\"\n[workspace]\n[package.metadata.lenso.contract]\ndescriptor = \"capability.json\"\nprojection = \"typescript\"\noutput = \"generated/text.ts\"\n",
        )
        .unwrap();

    synchronize(temp.path(), &[]).unwrap();
    assert!(root.join("generated/text.ts").is_file());
    assert_eq!(
        fs::read_to_string(root.join("src/contract.rs")).unwrap(),
        "pub fn unrelated() {}\n"
    );
}

#[test]
#[ignore = "requires Cargo registry access; compiles actual source extraction"]
fn clean_room_source_contract_generates_before_a_stale_library_can_compile() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("contracts/text");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        r#"
[package]
name = "source-text-contract"
version = "1.0.0"
edition = "2024"
[workspace]
[package.metadata.lenso.contract]
descriptor = "capability.json"
source = "src/contract.rs"
projection = "typescript"
output = "generated/text.ts"
[dependencies]
schemars = "1.2"
lenso-contract-authoring = "=0.1.2"
[build-dependencies]
lenso-contract-codegen = "=0.10.1"
"#,
    )
    .unwrap();
    fs::write(
        root.join("src/lib.rs"),
        "compile_error!(\"stale consumer must not compile during extraction\");",
    )
    .unwrap();
    fs::write(root.join("src/contract.rs"), r#"
use lenso_contract_authoring as lenso;
#[derive(lenso::JsonSchema)]
#[schemars(deny_unknown_fields)]
struct Input { text: String }
#[derive(lenso::DomainError)]
enum Error { Unavailable }
#[lenso::capability(id = "example.text", major = 1, version = "1.0.0", portable = true, cross_lane_transfer = false)]
trait Text {
    async fn uppercase(&self, context: lenso::Ctx<'_>, request: Input) -> Result<Input, Error>;
}
"#).unwrap();
    synchronize(temp.path(), &[]).unwrap();
    assert!(root.join("capability.json").is_file());
    assert!(
        fs::read_to_string(root.join("generated/text.ts"))
            .unwrap()
            .contains("uppercase")
    );
    synchronize(temp.path(), &[]).unwrap();
}
