use crate::{ContractAuthoring, ContractInput, digest, discovery::contained};
use anyhow::{Context, ensure};
use lenso_engine::{Engine, Generation, Resource, Snapshot, publication::FileResource};
use serde::{Deserialize, Serialize};
use std::{
    collections::BTreeMap,
    fs,
    path::Path,
    sync::{Arc, atomic::AtomicBool},
};

#[derive(Clone, Copy, Debug)]
pub enum Mode {
    Generate,
    Check,
}

/// Validate all destinations before changing any projection. Check never writes.
/// Unchanged projections, including compatible prebuilt outputs, retain mtimes.
pub fn apply(root: &Path, generation: &Generation, mode: Mode) -> anyhow::Result<()> {
    let mut outputs = BTreeMap::new();
    for resources in generation.outputs.values() {
        for resource in resources.values() {
            ensure!(
                resource.schema == "lenso.engine.file.v1",
                "unexpected contract resource"
            );
            let file: FileResource = serde_json::from_value(resource.value.clone())?;
            contained(root, &file.path)?;
            ensure!(
                String::from_utf8_lossy(&file.bytes)
                    .lines()
                    .take(3)
                    .any(|line| line.contains("@generated by lenso-contract-codegen")),
                "invalid generated projection"
            );
            ensure!(
                outputs.insert(file.path.clone(), file.bytes).is_none(),
                "duplicate output {}",
                file.path
            );
        }
    }
    let mut changes = Vec::new();
    for (path, bytes) in outputs {
        let target = root.join(&path);
        let old = match fs::read(&target) {
            Ok(old) => Some(old),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
            Err(error) => return Err(error.into()),
        };
        if old.as_ref() == Some(&bytes) {
            continue;
        }
        ensure!(
            matches!(mode, Mode::Generate),
            "stale or missing contract projection: {path}"
        );
        if let Some(previous) = &old {
            ensure!(
                String::from_utf8_lossy(previous)
                    .lines()
                    .take(3)
                    .any(|line| line.contains("@generated by lenso-contract-codegen")),
                "refusing to overwrite authored file: {path}"
            );
        }
        changes.push((target, bytes, old));
    }
    for (target, bytes, _) in &changes {
        let result = (|| -> anyhow::Result<()> {
            fs::create_dir_all(target.parent().context("projection parent")?)?;
            let mut stage = tempfile::NamedTempFile::new_in(target.parent().unwrap())?;
            use std::io::Write;
            stage.write_all(bytes)?;
            stage.persist(target)?;
            Ok(())
        })();
        if let Err(error) = result {
            for (path, _, old) in &changes {
                if let Some(old) = old {
                    let _ = fs::write(path, old);
                } else {
                    let _ = fs::remove_file(path);
                }
            }
            return Err(error);
        }
    }
    Ok(())
}

#[derive(Serialize, Deserialize)]
struct Cache {
    key: String,
    digest: String,
    outputs: BTreeMap<String, BTreeMap<String, Resource>>,
}

/// Execute selected inputs with an optional consumer-owned, content-addressed
/// cache. Inputs must already be locked/materialized; this never fetches packages.
/// Check reads an existing cache but does not create or repair one.
pub fn run(
    snapshot: Snapshot,
    inputs: Vec<ContractInput>,
    output_root: &Path,
    cache_root: Option<&Path>,
    mode: Mode,
) -> anyhow::Result<Generation> {
    let processor = ContractAuthoring::from_inputs(inputs)?;
    if let Some(cache) = cache_root
        && let Ok(path) = cache.strip_prefix(output_root)
        && !path.as_os_str().is_empty()
    {
        contained(output_root, path.to_str().context("UTF8 cache path")?)?;
    }
    use lenso_engine::Plugin;
    let key = digest(&serde_json::to_vec(&(processor.identity(), &snapshot))?);
    let mut engine = Engine::default();
    engine.register(processor)?;
    let plan = engine.plan(snapshot)?;
    let cached = cache_root.and_then(|root| {
        let path = format!("{key}.json");
        contained(root, &path).ok()?;
        let metadata = fs::metadata(root.join(&path)).ok()?;
        if !metadata.is_file() || metadata.len() > 16 * 1024 * 1024 {
            return None;
        }
        let cache: Cache = serde_json::from_slice(&fs::read(root.join(path)).ok()?).ok()?;
        if cache.key != key || digest(&serde_json::to_vec(&cache.outputs).ok()?) != cache.digest {
            return None;
        }
        Some(Generation {
            outputs: cache.outputs,
            ..Generation::default()
        })
    });
    let generation = match cached {
        Some(generation) => generation,
        None => engine.execute(&plan, &Arc::new(AtomicBool::new(false)))?,
    };
    apply(output_root, &generation, mode)?;
    if let Some(root) = cache_root
        && matches!(mode, Mode::Generate)
    {
        fs::create_dir_all(root)?;
        contained(root, &format!("{key}.json"))?;
        let cache = Cache {
            key: key.clone(),
            digest: digest(&serde_json::to_vec(&generation.outputs)?),
            outputs: generation.outputs.clone(),
        };
        let mut stage = tempfile::NamedTempFile::new_in(root)?;
        use std::io::Write;
        stage.write_all(&serde_json::to_vec(&cache)?)?;
        stage.persist(root.join(format!("{key}.json")))?;
    }
    Ok(generation)
}
