use lenso_engine::Snapshot;
use lenso_engine_contracts::{
    ContractInput, DiscoveryOptions, Mode, Projection, ProjectionKind, ProjectionTarget, discover,
    run, snapshot_contract,
};
use std::{
    fs,
    path::{Path, PathBuf},
};

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/profile")
}

#[test]
fn web_and_contract_readers_share_overlapping_directory_acquisition() {
    use lenso_engine::discovery::DiscoverySession;
    use lenso_engine_contracts::discover_in;
    use lenso_engine_web::{WebOptions, read_sources_in};
    let root = tempfile::tempdir().unwrap();
    let mut inputs = Snapshot::default();
    snapshot_contract(
        &fixture(),
        "capability.json",
        "inputs/profile/capability.json",
        &mut inputs,
    )
    .unwrap();
    for (path, bytes) in inputs.files() {
        let path = root.path().join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, bytes).unwrap();
    }
    fs::write(
        root.path().join("inputs/health.rs"),
        "#[get(\"/health\")] async fn health(&self) {}\n",
    )
    .unwrap();
    let mut session = DiscoverySession::new(root.path()).unwrap();
    let web = read_sources_in(
        &mut session,
        &WebOptions {
            roots: vec!["inputs".into()],
            ..Default::default()
        },
    )
    .unwrap();
    let (contracts, _) = discover_in(
        &mut session,
        &DiscoveryOptions {
            roots: vec!["inputs".into()],
            baseline_root: None,
            ..Default::default()
        },
    )
    .unwrap();
    assert_eq!(session.stats().directory_reads, 3);
    assert_eq!(
        session.stats().file_reads,
        web.files().len() + contracts.files().len()
    );
    for path in contracts.files().keys() {
        session.read(path, 4 * 1024 * 1024).unwrap();
    }
    assert_eq!(
        session.stats().file_reads,
        web.files().len() + contracts.files().len()
    );
}
fn selected(snapshot: &mut Snapshot, prefix: &str) -> ContractInput {
    let descriptor = format!("{prefix}/capability.json");
    snapshot_contract(&fixture(), "capability.json", &descriptor, snapshot).unwrap();
    ContractInput {
        identity: "registry+locked-profile#1.0.0/checksum-123".into(),
        descriptor,
        baseline: None,
        projections: vec![Projection {
            kind: ProjectionKind::RustRuntime,
            output: "consumer/profile.rs".into(),
            module: Some("profile".into()),
        }],
    }
}
#[test]
fn immutable_dependency_input_generates_scoped_output_and_offline_cache() {
    let output = tempfile::tempdir().unwrap();
    let cache = output.path().join("cache");
    let before = fs::read(fixture().join("capability.json")).unwrap();
    let mut snapshot = Snapshot::default();
    let input = selected(&mut snapshot, "deps/profile");
    run(
        snapshot.clone(),
        vec![input.clone()],
        output.path(),
        Some(&cache),
        Mode::Generate,
    )
    .unwrap();
    let generated = fs::read(output.path().join("consumer/profile.rs")).unwrap();
    let expected = lenso_contract_codegen::generate_module_projection(
        &fixture().join("capability.json"),
        lenso_contract_codegen::ProjectionLanguage::RustRuntime,
        "profile",
    )
    .unwrap()
    .source;
    assert_eq!(generated, expected.as_bytes());
    assert_eq!(fs::read(fixture().join("capability.json")).unwrap(), before);
    assert_eq!(fs::read_dir(&cache).unwrap().count(), 1);
    run(
        snapshot.clone(),
        vec![input.clone()],
        output.path(),
        Some(&cache),
        Mode::Check,
    )
    .unwrap();
    fs::write(
        output.path().join("consumer/profile.rs"),
        "// @generated by lenso-contract-codegen\nstale",
    )
    .unwrap();
    assert!(
        run(
            snapshot.clone(),
            vec![input.clone()],
            output.path(),
            Some(&cache),
            Mode::Check
        )
        .is_err()
    );
    run(
        snapshot,
        vec![input],
        output.path(),
        Some(&cache),
        Mode::Generate,
    )
    .unwrap();
    assert_eq!(
        fs::read(output.path().join("consumer/profile.rs")).unwrap(),
        generated
    );
}
#[test]
fn custom_discovery_output_modules_and_exclusion_are_effective() {
    let root = tempfile::tempdir().unwrap();
    let mut snapshot = Snapshot::default();
    snapshot_contract(
        &fixture(),
        "capability.json",
        "interfaces/profile/interface.json",
        &mut snapshot,
    )
    .unwrap();
    // snapshot_contract copies JSON under original filename; custom reader input
    // can choose its own descriptor path without any filename recognition.
    for (path, bytes) in snapshot.files() {
        let output = root.path().join(path);
        fs::create_dir_all(output.parent().unwrap()).unwrap();
        fs::write(output, bytes).unwrap();
    }
    fs::create_dir_all(root.path().join("interfaces/ignored")).unwrap();
    fs::write(
        root.path().join("interfaces/ignored/interface.json"),
        "invalid",
    )
    .unwrap();
    let options = DiscoveryOptions {
        roots: vec!["interfaces".into()],
        descriptor_filename: "interface.json".into(),
        exclude: vec!["interfaces/ignored".into()],
        targets: vec![ProjectionTarget {
            kind: ProjectionKind::TypeScript,
            output: "client/{name}.ts".into(),
            module: None,
        }],
        ..Default::default()
    };
    let (snapshot, inputs) = discover(root.path(), &options).unwrap();
    assert_eq!(inputs.len(), 1);
    run(snapshot, inputs, root.path(), None, Mode::Generate).unwrap();
    assert!(root.path().join("client/profile.ts").exists());
}
#[test]
fn compatibility_and_output_ownership_fail_before_any_write() {
    let root = tempfile::tempdir().unwrap();
    let mut snapshot = Snapshot::default();
    let mut input = selected(&mut snapshot, "current");
    snapshot_contract(
        &fixture(),
        "capability.json",
        "old/capability.json",
        &mut snapshot,
    )
    .unwrap();
    let mut next: serde_json::Value =
        serde_json::from_slice(&snapshot.files()["current/capability.json"]).unwrap();
    next["operations"].as_array_mut().unwrap().remove(0);
    let mut updated = Snapshot::default();
    for (path, bytes) in snapshot.files() {
        updated
            .insert(
                path.clone(),
                if path == "current/capability.json" {
                    serde_json::to_vec(&next).unwrap()
                } else {
                    bytes.clone()
                },
            )
            .unwrap();
    }
    input.baseline = Some("old/capability.json".into());
    assert!(
        run(
            updated,
            vec![input.clone()],
            root.path(),
            None,
            Mode::Generate
        )
        .is_err()
    );
    assert!(!root.path().join("consumer").exists());
    input.baseline = None;
    assert!(
        run(
            snapshot.clone(),
            vec![input.clone(), input.clone()],
            root.path(),
            None,
            Mode::Generate
        )
        .is_err()
    );
    fs::create_dir_all(root.path().join("consumer")).unwrap();
    fs::write(root.path().join("consumer/profile.rs"), "authored").unwrap();
    assert!(run(snapshot, vec![input], root.path(), None, Mode::Generate).is_err());
    assert_eq!(
        fs::read_to_string(root.path().join("consumer/profile.rs")).unwrap(),
        "authored"
    );
}
#[cfg(unix)]
#[test]
fn symlinked_inputs_outputs_and_cache_are_rejected() {
    let root = tempfile::tempdir().unwrap();
    let outside = tempfile::tempdir().unwrap();
    std::os::unix::fs::symlink(outside.path(), root.path().join("consumer")).unwrap();
    let mut snapshot = Snapshot::default();
    let input = selected(&mut snapshot, "input");
    assert!(run(snapshot, vec![input], root.path(), None, Mode::Generate).is_err());
    assert!(fs::read_dir(outside.path()).unwrap().next().is_none());
}

#[test]
fn accepted_baseline_rejects_breaking_generation_without_advancing() {
    let root = tempfile::tempdir().unwrap();
    let mut snapshot = Snapshot::default();
    selected(&mut snapshot, "contracts/profile");
    for (path, bytes) in snapshot.files() {
        let file = root.path().join(path);
        fs::create_dir_all(file.parent().unwrap()).unwrap();
        fs::write(file, bytes).unwrap();
    }
    let options = DiscoveryOptions::default();
    let (snapshot, inputs) = discover(root.path(), &options).unwrap();
    run(
        snapshot.clone(),
        inputs.clone(),
        root.path(),
        None,
        Mode::Generate,
    )
    .unwrap();
    lenso_engine_contracts::accept(
        root.path(),
        options.baseline_root.as_deref().unwrap(),
        &snapshot,
        &inputs,
    )
    .unwrap();
    let current = root.path().join(".lenso/contracts/accepted/current.json");
    let accepted = fs::read(&current).unwrap();
    let (snapshot, inputs) = discover(root.path(), &options).unwrap();
    run(snapshot, inputs, root.path(), None, Mode::Check).unwrap();
    let descriptor = root.path().join("contracts/profile/capability.json");
    let mut next: serde_json::Value =
        serde_json::from_slice(&fs::read(&descriptor).unwrap()).unwrap();
    next["operations"].as_array_mut().unwrap().remove(0);
    fs::write(descriptor, serde_json::to_vec(&next).unwrap()).unwrap();
    let (snapshot, inputs) = discover(root.path(), &options).unwrap();
    assert!(inputs[0].baseline.is_some());
    assert!(run(snapshot, inputs, root.path(), None, Mode::Generate).is_err());
    assert_eq!(fs::read(current).unwrap(), accepted);
}
#[test]
fn shared_discovery_epoch_reuses_descriptor_schema_reads_and_parses() {
    use lenso_engine::{Snapshot, discovery::DiscoverySession};
    use lenso_engine_contracts::{DiscoveryOptions, discover_in, snapshot_contract_in};
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let mut session = DiscoverySession::new(&root).unwrap();
    let options = DiscoveryOptions {
        roots: vec!["profile".into(), "profile/schemas".into()],
        baseline_root: None,
        ..Default::default()
    };
    let (snapshot, inputs) = discover_in(&mut session, &options).unwrap();
    assert_eq!(inputs.len(), 1);
    let first = session.stats();
    assert_eq!(first.file_reads, snapshot.files().len());
    assert_eq!(first.json_parses, first.file_reads);
    discover_in(&mut session, &options).unwrap();
    let mut other = Snapshot::default();
    snapshot_contract_in(
        &mut session,
        "profile/capability.json",
        "renamed/capability.json",
        &mut other,
    )
    .unwrap();
    assert_eq!(session.stats(), first);
    assert_eq!(snapshot.files().len(), other.files().len());
    session.begin_epoch();
    discover_in(&mut session, &options).unwrap();
    assert_eq!(session.stats(), first);
}
