//! Retain Cargo diagnostics and attribute generated route bodies to authored handlers.
use std::{
    collections::BTreeSet,
    env, fs,
    future::Future,
    io::{BufRead as _, BufReader},
    path::Path,
    process::Stdio,
};

use anyhow::{Context, bail};
use quote::ToTokens as _;
use serde_json::Value;
use syn::spanned::Spanned as _;

pub(super) fn build(
    project: &Path,
    target: &Path,
    source: &Path,
    plugin_manifest: &Path,
) -> anyhow::Result<()> {
    let mut child = command(project, target)
        .stdout(Stdio::piped())
        .spawn()
        .context("build Web development Host")?;
    let output = child.stdout.take().context("read Cargo diagnostics")?;
    let read = (|| {
        for line in BufReader::new(output).lines() {
            let line = line.context("read Cargo diagnostic")?;
            render(&line, source, plugin_manifest);
        }
        Ok::<_, anyhow::Error>(())
    })();
    // Reap Cargo even when diagnostic reading fails.
    let status = child.wait().context("wait for Web development build")?;
    read?;
    if !status.success() {
        bail!("build Web development Host failed with {status}");
    }
    Ok(())
}

pub(super) async fn build_for_dev(
    project: &Path,
    target: &Path,
    source: &Path,
    plugin_manifest: &Path,
    shutdown: &mut (impl Future<Output = std::io::Result<()>> + Unpin),
) -> anyhow::Result<bool> {
    super::build_process::run(
        command(project, target),
        "build Web development Host",
        shutdown,
        |line| render(line, source, plugin_manifest),
    )
    .await
}

fn command(project: &Path, target: &Path) -> std::process::Command {
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut command = crate::app::build_command(cargo);
    command
        .args(["build", "--locked", "--message-format=json"])
        .env("CARGO_TARGET_DIR", target)
        .current_dir(project);
    command
}

fn render(line: &str, source: &Path, plugin_manifest: &Path) {
    let Ok(message) = serde_json::from_str::<Value>(line) else {
        eprintln!("{line}");
        return;
    };
    if message["reason"] != "compiler-message" {
        return;
    }
    if let Some(rendered) = message["message"]["rendered"].as_str() {
        eprint!("{rendered}");
    }
    for origin in origins(source, plugin_manifest, &message) {
        eprintln!("note: generated Web handler source: {origin}");
    }
}

fn origins(root: &Path, plugin_manifest: &Path, message: &Value) -> BTreeSet<String> {
    let mut origins = BTreeSet::new();
    // Dependency diagnostics can contain identical generated bodies. Attribute
    // only messages from the exact Plugin source passed to this Host's Cargo build.
    if message["manifest_path"]
        .as_str()
        .and_then(|path| fs::canonicalize(path).ok())
        .as_deref()
        != Some(plugin_manifest)
    {
        return origins;
    }
    let Some(spans) = message["message"]["spans"].as_array() else {
        return origins;
    };
    for span in spans.iter().filter(|span| span["is_primary"] == true) {
        let (Some(path), Some(offset)) = (span["file_name"].as_str(), span["byte_start"].as_u64())
        else {
            continue;
        };
        let path = Path::new(path);
        let Ok(offset) = usize::try_from(offset) else {
            continue;
        };
        let Some(body) = generated_body(path, offset) else {
            continue;
        };
        if let Some(origin) = authored_origin(root, &body) {
            origins.insert(origin);
        }
    }
    origins
}

fn generated_body(path: &Path, offset: usize) -> Option<String> {
    let source = bounded_source(path)?;
    if !source.starts_with("// @generated by lenso-engine-web\n") {
        return None;
    }
    let file = syn::parse_file(&source).ok()?;
    for item in file.items {
        if let syn::Item::Impl(item) = item {
            for method in item.items {
                if let syn::ImplItem::Fn(method) = method
                    && method.span().byte_range().contains(&offset)
                {
                    return Some(method.block.to_token_stream().to_string());
                }
            }
        }
    }
    None
}

fn bounded_source(path: &Path) -> Option<String> {
    let metadata = fs::symlink_metadata(path).ok()?;
    if !metadata.is_file() || metadata.len() > 1024 * 1024 {
        return None;
    }
    fs::read_to_string(path).ok()
}

fn authored_origin(root: &Path, body: &str) -> Option<String> {
    let mut pending = vec![root.join("src")];
    let mut origin = None;
    let mut visited = 0;
    while let Some(path) = pending.pop() {
        visited += 1;
        if visited > 4096 {
            return None;
        }
        let metadata = fs::symlink_metadata(&path).ok()?;
        if metadata.is_dir() {
            for entry in fs::read_dir(path).ok()? {
                pending.push(entry.ok()?.path());
            }
        } else if path.extension().is_some_and(|extension| extension == "rs")
            && let Some(source) = bounded_source(&path)
            && let Ok(file) = syn::parse_file(&source)
        {
            for item in file.items {
                if let syn::Item::Fn(handler) = item
                    && handler.block.to_token_stream().to_string() == body
                {
                    // Identical bodies in different handlers are ambiguous: retain only
                    // Cargo's real location rather than guessing an authored location.
                    if origin.is_some() {
                        return None;
                    }
                    let line = handler.sig.ident.span().start().line;
                    origin = Some(format!("{}:{line} ({})", path.display(), handler.sig.ident));
                }
            }
        }
    }
    origin
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ambiguous_authored_bodies_do_not_misattribute_a_generated_error() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir(root.path().join("src")).unwrap();
        let generated = root.path().join("web_routes.rs");
        let text =
            "// @generated by lenso-engine-web\nimpl Web { fn route(&self) { missing(); } }\n";
        fs::write(&generated, text).unwrap();
        let body = generated_body(&generated, text.find("missing").unwrap()).unwrap();
        let path = root.path().join("src/route.rs");
        fs::write(&path, "\nfn route(&self) { missing(); }\n").unwrap();
        assert!(
            authored_origin(root.path(), &body)
                .unwrap()
                .contains("route.rs:2 (route)")
        );
        fs::write(
            root.path().join("src/other.rs"),
            "fn other(&self) { missing(); }",
        )
        .unwrap();
        assert!(authored_origin(root.path(), &body).is_none());
    }

    #[test]
    fn dependency_diagnostics_do_not_point_to_a_matching_local_handler() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir(root.path().join("src")).unwrap();
        let manifest = root.path().join("Cargo.toml");
        fs::write(&manifest, "").unwrap();
        let manifest = fs::canonicalize(manifest).unwrap();
        fs::write(
            root.path().join("src/route.rs"),
            "fn route() { missing(); }",
        )
        .unwrap();
        let dependency = tempfile::tempdir().unwrap();
        let generated = dependency.path().join("web_routes.rs");
        let source = "// @generated by lenso-engine-web\nimpl Web { fn route() { missing(); } }";
        fs::write(&generated, source).unwrap();
        let foreign_manifest = dependency.path().join("Cargo.toml");
        fs::write(&foreign_manifest, "").unwrap();
        let mut message = serde_json::json!({
            "manifest_path": foreign_manifest,
            "message": { "spans": [{
                "is_primary": true,
                "file_name": generated,
                "byte_start": source.find("missing").unwrap(),
            }] },
        });
        assert!(origins(root.path(), &manifest, &message).is_empty());
        message["manifest_path"] = serde_json::json!(manifest);
        assert_eq!(origins(root.path(), &manifest, &message).len(), 1);
        message["manifest_path"] = Value::Null;
        assert!(origins(root.path(), &manifest, &message).is_empty());
    }
}
