use crate::{RouteSet, WebOptions, compile};
use anyhow::{Context, ensure};
use lenso_engine::{Snapshot, discovery::DiscoverySession, publication::FileResource};
use std::{fs, path::Path};

fn selected(options: &WebOptions, path: &str) -> bool {
    !options
        .exclude
        .iter()
        .any(|excluded| path == excluded || path.starts_with(&format!("{excluded}/")))
}
fn contained(root: &Path, path: &str) -> anyhow::Result<()> {
    lenso_engine::Resource::file(path.into(), vec![])?;
    ensure!(
        fs::symlink_metadata(root)?.is_dir(),
        "root must be a real directory"
    );
    let mut current = root.to_path_buf();
    for part in Path::new(path).components() {
        current.push(part);
        match fs::symlink_metadata(&current) {
            Ok(metadata) => ensure!(
                !metadata.file_type().is_symlink(),
                "symlink in Web authoring path: {}",
                current.display()
            ),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    Ok(())
}
/// Default bounded filesystem reader. Custom discovery can construct Snapshot
/// directly and use compile(), including inputs from formats or roots of its own.
pub fn read_sources(root: &Path, options: &WebOptions) -> anyhow::Result<Snapshot> {
    read_sources_in(&mut DiscoverySession::new(root)?, options)
}

/// Share acquisition with other readers while retaining this selection policy.
pub fn read_sources_in(
    session: &mut DiscoverySession,
    options: &WebOptions,
) -> anyhow::Result<Snapshot> {
    let mut snapshot = Snapshot::default();
    let mut visited = 0;
    let roots = options
        .roots
        .iter()
        .chain(&options.filesystem_roots)
        .cloned()
        .collect::<Vec<_>>();
    for path in if options.entries.is_empty() {
        &roots
    } else {
        &options.entries
    } {
        if !selected(options, path) {
            continue;
        }
        contained(session.root(), path)?;
        read(session, path, options, &mut snapshot, &mut visited, 0)?;
    }
    Ok(snapshot)
}
fn read(
    session: &mut DiscoverySession,
    path: &str,
    options: &WebOptions,
    snapshot: &mut Snapshot,
    visited: &mut usize,
    depth: usize,
) -> anyhow::Result<()> {
    if !selected(options, path) {
        return Ok(());
    }
    *visited += 1;
    ensure!(
        *visited <= 4096 && depth <= 32,
        "Web source traversal exceeds budget"
    );
    let metadata = fs::symlink_metadata(session.root().join(path))?;
    ensure!(
        !metadata.file_type().is_symlink(),
        "Web source symlink: {path}"
    );
    if metadata.is_dir() {
        for entry in session.directory(path)? {
            read(session, &entry.path, options, snapshot, visited, depth + 1)?;
        }
    } else {
        ensure!(
            metadata.is_file(),
            "Web input must be a file/directory: {path}"
        );
        if (!options.entries.is_empty() || path.ends_with(".rs"))
            && !snapshot.files().contains_key(path)
        {
            ensure!(metadata.len() <= 1024 * 1024, "route file exceeds 1 MiB");
            snapshot.insert(path.into(), session.read(path, 1024 * 1024)?.to_vec())?;
        }
    }
    Ok(())
}

/// Build-script convenience. Output belongs in OUT_DIR or a consumer-owned
/// staging directory, separate from authored sources. Returns validated inventory.
pub fn build(root: &Path, output: &Path, options: WebOptions) -> anyhow::Result<RouteSet> {
    let snapshot = read_sources(root, &options)?;
    let generation = compile(snapshot, options)?;
    fs::create_dir_all(output)?;
    let resources = generation.outputs.get("web/routes").context("Web output")?;
    let inventory: RouteSet = serde_json::from_value(resources["routes"].value.clone())?;
    let file: FileResource = serde_json::from_value(resources["bindings"].value.clone())?;
    contained(output, &file.path)?;
    let target = output.join(file.path);
    if let Ok(previous) = fs::read(&target) {
        ensure!(
            previous.starts_with(b"// @generated by lenso-engine-web"),
            "refusing to overwrite authored Web file"
        );
        if previous == file.bytes {
            return Ok(inventory);
        }
    }
    fs::create_dir_all(target.parent().context("Web output parent")?)?;
    fs::write(target, file.bytes)?;
    Ok(inventory)
}
