import { readdir, readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineEnginePlugin } from "@lenso/engine/authoring";

/** App-installed build plugin: discover Markdown and generate a static data module. */
export function contentPlugin(directory = "content") {
  return defineEnginePlugin({
    name: "example/content",
    source: { file: fileURLToPath(import.meta.url), export: "contentPlugin" },
    setup(context) {
      context.watch(directory); // Includes additions/removals, not only current source files.
      context.discover("markdown", async ({ root }) =>
        (await readdir(join(root, directory)))
          .filter((file) => file.endsWith(".md"))
          .sort()
          .map((file) => join(directory, file)),
      );
      context.generate("content", async ({ sources }) => {
        const documents = await Promise.all(
          sources
            .filter((file) => file.endsWith(".md"))
            .map(async (file) => ({
              slug: basename(file, ".md"),
              body: await readFile(file, "utf8"),
            })),
        );
        return [
          {
            path: "content.ts",
            content: `// Generated by example/content.\nexport const documents = ${JSON.stringify(documents, null, 2)} as const;\n`,
          },
        ];
      });
    },
  });
}
