import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { discover, generate } from "../src/engine";
import { readApplication } from "../src/application";
import { EngineError, diagnostic } from "../src/diagnostics";

const directories: string[] = [];
afterEach(async () => {
  for (const directory of directories.splice(0))
    await rm(directory, { recursive: true, force: true });
});
async function fixture(config: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "lenso-engine-"));
  directories.push(root);
  await Bun.write(join(root, "lenso.config.ts"), config);
  return root;
}

describe("static assembly", () => {
  test("discovers topological order without initializing plugin business code", async () => {
    const root = await fixture(`
      const dependency = { id: 'dependency', setup() { throw new Error('setup must never run'); } };
      const dependent = { id: 'dependent', requires: [dependency], setup() { throw new Error('setup must never run'); } };
      export default { plugins: [dependent, dependency] };
    `);
    expect((await discover(root)).ordered.map((plugin) => plugin.id)).toEqual([
      "dependency",
      "dependent",
    ]);
  });

  test.each([
    [
      "duplicate identities",
      `export default { plugins: [{ id: 'a', setup() {} }, { id: 'a', setup() {} }] };`,
    ],
    [
      "missing dependencies",
      `const b = { id: 'b', setup() {} }; export default { plugins: [{ id: 'a', requires: [b], setup() {} }] };`,
    ],
    [
      "cycles",
      `const a = { id: 'a', requires: [], setup() {} }; const b = { id: 'b', requires: [a], setup() {} }; a.requires.push(b); export default { plugins: [a,b] };`,
    ],
  ])("rejects %s at discovery time and retains assembly errors", async (_name, config) => {
    const root = await fixture(config);
    const error = await discover(root).catch((cause: unknown) => cause);
    expect(error).toBeInstanceOf(EngineError);
    expect((error as EngineError).cause).toBeInstanceOf(Error);
    expect(diagnostic(error).code).toBe("invalid-assembly");
    expect(await Bun.file(join(root, ".lenso/manifest.json")).exists()).toBe(false);
  });

  test("generates separate browser client and server entries", async () => {
    const root = await fixture(
      `export default { plugins: [{ id: 'greeting', setup() {}, contributions: [{ kind: 'example.metadata', label: 'Greeting' }] }] };`,
    );
    await mkdir(join(root, "src"));
    await Bun.write(join(root, "src/router.ts"), "export type AppRouter = {};");
    await generate(root);
    const client = await Bun.file(join(root, ".lenso/client.ts")).text();
    expect(client).toContain("from '@lenso/web/client'");
    expect(client).toContain("import type { AppRouter }");
    expect(client).not.toContain("lenso.config");
    expect(client).not.toContain("startApp");
    expect(await Bun.file(join(root, ".lenso/server.ts")).text()).toContain("../lenso.config");
  });
});

test("lightweight application reading does not load Engine config or run setup", async () => {
  const root = await fixture(`
    const plugin = { id: 'static', setup() { throw new Error('must not start'); } };
    export const operations = [{plugin, method:'run', description:'Runtime input only', input:{'~standard':{version:1,vendor:'test',validate:value=>({value})}}}];
    export default {plugins:[plugin]};
  `);
  await Bun.write(join(root, "lenso.engine.ts"), "throw Error('must not load Engine');");
  const discovery = await readApplication(root, join(root, "lenso.config.ts"));
  expect(discovery.ordered.map((plugin) => plugin.id)).toEqual(["static"]);
  expect(discovery.app.operations?.[0]?.method).toBe("run");
});

test("application import failures retain the exact original error", async () => {
  const root = await fixture(`
    export const failure = new Error('token=private-config');
    export default { get plugins() { throw failure; } };
  `);
  const module = await import(join(root, "lenso.config.ts"));
  // A separate throwing module exercises the import boundary, not config validation getters.
  const failing = join(root, "failing.ts");
  await Bun.write(failing, `import {failure} from './lenso.config'; throw failure;`);
  const error = await readApplication(root, failing).catch((cause: unknown) => cause);
  expect(error).toBeInstanceOf(EngineError);
  expect((error as EngineError).cause).toBe(module.failure);
  expect(JSON.stringify(diagnostic(error))).not.toContain("private-config");
});

test("manifest and entry bytes retain the historical generator format", async () => {
  const root = await fixture("export default {plugins:[]};");
  await generate(root);
  const header = "// Generated by lenso-cli; run lenso generate after changing assembly.\n";
  expect(await Bun.file(join(root, ".lenso/server.ts")).text()).toBe(
    `${header}export { default as app } from "../lenso.config";\n`,
  );
  expect(await Bun.file(join(root, ".lenso/client.ts")).text()).toBe(`${header}export {};\n`);
  const manifest = await Bun.file(join(root, ".lenso/manifest.json")).text();
  expect(manifest).toBe(
    '{\n  "generatedBy": "lenso-cli",\n  "operations": [],\n  "plugins": [],\n  "schemaVersion": 1,\n  "source": "lenso.config.ts"\n}\n',
  );
  await generate(root);
  expect(await Bun.file(join(root, ".lenso/manifest.json")).text()).toBe(manifest);
});
