-- Publish the append-only Story Segment Feed after terminal workflow operations.
alter table platform.service_story_segments
    add column if not exists feed_sequence bigint generated by default as identity,
    add column if not exists story_id text,
    add column if not exists evidence_revision integer not null default 1,
    add column if not exists operation_kind text,
    add column if not exists contract_id text,
    add column if not exists contract_version text,
    add column if not exists attempt integer not null default 1,
    add column if not exists recorded_at timestamptz,
    add column if not exists tenant_id text,
    add column if not exists parent_segment_id text,
    add column if not exists causation_id text,
    add column if not exists workflow_instance_id text,
    add column if not exists workflow_definition_owner text,
    add column if not exists workflow_definition_name text,
    add column if not exists workflow_definition_version text,
    add column if not exists workflow_step_id text,
    add column if not exists parent_workflow_instance_id text,
    add column if not exists compensation_id text,
    add column if not exists intervention_id text;

update platform.service_story_segments
set story_id = coalesce(story_id, segment_id),
    operation_kind = coalesce(operation_kind, 'legacy'),
    contract_id = coalesce(contract_id, operation),
    contract_version = coalesce(contract_version, 'legacy'),
    recorded_at = coalesce(recorded_at, completed_at)
where story_id is null
   or operation_kind is null
   or contract_id is null
   or contract_version is null
   or recorded_at is null;

alter table platform.service_story_segments
    alter column story_id set not null,
    alter column operation_kind set not null,
    alter column contract_id set not null,
    alter column contract_version set not null,
    alter column recorded_at set not null;

alter table platform.service_story_segments
    drop constraint if exists service_story_segments_pkey;

drop index if exists platform.service_story_segments_background_outcome_idx;

alter table platform.service_story_segments
    add constraint service_story_segments_pkey primary key (feed_sequence),
    add constraint service_story_segments_identity_revision_key
        unique (service_id, segment_id, evidence_revision),
    add constraint service_story_segments_revision_check
        check (evidence_revision > 0),
    add constraint service_story_segments_attempt_check
        check (attempt > 0),
    add constraint service_story_segments_timestamps_check
        check (completed_at >= started_at and recorded_at >= started_at),
    add constraint service_story_segments_workflow_identity_check check (
        workflow_instance_id is null
        or (
            workflow_definition_owner is not null
            and workflow_definition_name is not null
            and workflow_definition_version is not null
        )
    );

create index if not exists service_story_segments_feed_idx
    on platform.service_story_segments (service_id, feed_sequence);

create index if not exists service_story_segments_tenant_feed_idx
    on platform.service_story_segments (service_id, tenant_id, feed_sequence);

create index if not exists service_story_segments_retention_idx
    on platform.service_story_segments (service_id, tenant_id, recorded_at, feed_sequence);

create or replace function platform.reject_story_segment_mutation()
returns trigger
language plpgsql
as $$
begin
    raise exception 'Story Segment Feed entries are append-only'
        using errcode = '55000';
end;
$$;

drop trigger if exists service_story_segments_append_only
    on platform.service_story_segments;

create trigger service_story_segments_append_only
before update or delete on platform.service_story_segments
for each row execute function platform.reject_story_segment_mutation();
