import { mkdir, access } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { startApp, validatePlugins, type Contribution, type Plugin } from "lenso";
import { CliError, diagnostic, environmentSecrets, redact, stableJson } from "./diagnostics";
import { describeOperation, validateOperations, type Operation } from "./operations";

export interface AppDefinition {
  readonly plugins: readonly Plugin<unknown>[];
  readonly operations?: readonly Operation[];
}
export interface PluginManifest {
  readonly id: string;
  readonly requires: readonly string[];
  readonly contributions: readonly Contribution[];
}
export interface Discovery {
  readonly root: string;
  readonly configPath: string;
  readonly app: AppDefinition;
  readonly ordered: readonly Plugin<unknown>[];
}

export async function discover(root = process.cwd()): Promise<Discovery> {
  const directory = resolve(root);
  const configPath = join(directory, "lenso.config.ts");
  let loaded;
  try {
    await access(configPath);
    loaded = await import(pathToFileURL(configPath).href);
  } catch (cause) {
    throw new CliError(
      {
        code: "config-load-failed",
        phase: "discovery",
        message: "Cannot load trusted lenso.config.ts.",
        source: { file: configPath },
      },
      3,
      { cause },
    );
  }
  const app: unknown = loaded.default;
  if (!app || typeof app !== "object" || !("plugins" in app) || !Array.isArray(app.plugins)) {
    throw new CliError(
      {
        code: "invalid-config",
        phase: "discovery",
        message: "lenso.config.ts must default-export defineApp({ plugins: [...] })",
        source: { file: configPath },
      },
      3,
    );
  }
  const definition = app as AppDefinition;
  let ordered: readonly Plugin<unknown>[];
  let operations: readonly Operation[];
  try {
    ordered = validatePlugins(definition.plugins);
    operations = validateOperations(
      definition.plugins,
      loaded.operations ?? definition.operations ?? [],
    );
  } catch (cause) {
    throw new CliError(diagnostic(cause, { source: { file: configPath } }), 3);
  }
  return {
    root: directory,
    configPath,
    app: { ...definition, operations },
    ordered,
  };
}

function sourceImport(fromDirectory: string, target: string): string {
  const path = relative(fromDirectory, target)
    .replaceAll("\\", "/")
    .replace(/\.(?:tsx?|jsx?)$/, "");
  return path.startsWith(".") ? path : `./${path}`;
}

async function writeGenerated(path: string, content: string): Promise<void> {
  const existing = Bun.file(path);
  if ((await existing.exists()) && (await existing.text()) === content) return;
  await Bun.write(path, content);
}

/** Discovers and writes static imports only. Plugin setup never runs at build time. */
export async function generate(root = process.cwd()): Promise<readonly PluginManifest[]> {
  const discovery = await discover(root);
  const directory = join(discovery.root, ".lenso");
  const manifest: readonly PluginManifest[] = discovery.ordered.map((plugin) => ({
    id: plugin.id,
    requires: (plugin.requires ?? []).map((dependency) => dependency.id),
    contributions: plugin.contributions ?? [],
  }));
  const manifestData = {
    schemaVersion: 1,
    generatedBy: "lenso-cli",
    source: "lenso.config.ts",
    plugins: manifest,
    operations: (discovery.app.operations ?? []).map((operation) =>
      describeOperation(operation, "lenso.config.ts"),
    ),
  };
  // Validate before redaction so unsupported/cyclic values cannot become successful output.
  stableJson(manifestData);
  const manifestJson = `${stableJson(redact(manifestData, environmentSecrets()), 2)}\n`;
  await mkdir(directory, { recursive: true });
  const header = "// Generated by lenso-cli; run lenso generate after changing assembly.\n";
  await writeGenerated(join(directory, "manifest.json"), manifestJson);
  await writeGenerated(
    join(directory, "server.ts"),
    `${header}export { default as app } from ${JSON.stringify(sourceImport(directory, discovery.configPath))};\n`,
  );
  const routerPath = join(discovery.root, "src/router.ts");
  if (await Bun.file(routerPath).exists()) {
    await writeGenerated(
      join(directory, "client.ts"),
      `${header}import { createClient as createWebClient } from '@lenso/web/client';\nimport type { AppRouter } from ${JSON.stringify(sourceImport(directory, routerPath))};\nexport type { AppRouter };\nexport const createClient = (url: string) => createWebClient<AppRouter>(url);\n`,
    );
  } else {
    // A stable empty browser entry prevents a removed Web integration leaving stale imports.
    await writeGenerated(join(directory, "client.ts"), `${header}export {};\n`);
  }
  return manifest;
}

export async function build(root = process.cwd(), entry?: string): Promise<string> {
  await generate(root);
  const directory = resolve(root);
  const conventionalEntry = join(directory, "src/server.ts");
  const entryPath = entry
    ? resolve(directory, entry)
    : (await Bun.file(conventionalEntry).exists())
      ? conventionalEntry
      : join(directory, ".lenso/server.ts");
  const outdir = join(directory, "dist");
  let result;
  try {
    result = await Bun.build({
      entrypoints: [entryPath],
      outdir,
      target: "bun",
      sourcemap: "external",
      packages: "external",
    });
  } catch (cause) {
    throw new CliError(
      {
        code: "build-failed",
        phase: "build",
        message: "Application build failed.",
        source: { file: entryPath },
      },
      1,
      { cause },
    );
  }
  if (!result.success)
    throw new CliError({
      code: "build-failed",
      phase: "build",
      message: "Application build failed.",
      causes: result.logs.map((log) => ({
        code: "build-diagnostic",
        phase: "build",
        message: "Bun build diagnostic; inspect the source location.",
        ...(log.position
          ? {
              source: {
                file: log.position.file,
                line: log.position.line,
                column: log.position.column,
              },
            }
          : { source: { file: entryPath } }),
      })),
    });
  return outdir;
}

export async function invoke(
  app: AppDefinition,
  pluginId: string,
  method: string,
  input: unknown,
): Promise<unknown> {
  const plugin = app.plugins.find((candidate) => candidate.id === pluginId);
  if (!plugin)
    throw new CliError(
      { code: "unknown-plugin", phase: "discovery", message: "Unknown plugin.", pluginId },
      3,
    );
  const operations = validateOperations(app.plugins, app.operations ?? []);
  const operation = operations.find(
    (candidate) => candidate.plugin === plugin && candidate.method === method,
  );
  const context = {
    pluginId,
    operation: `${pluginId}.${method}`,
    ...(operation?.source ? { source: operation.source } : {}),
  };
  if (!operation)
    throw new CliError(
      {
        code: "unknown-operation",
        phase: "discovery",
        message: "Service method is not explicitly exposed for CLI invocation.",
        ...context,
      },
      3,
    );
  let validated;
  try {
    validated = await operation.input["~standard"].validate(input);
  } catch (cause) {
    throw new CliError(
      { code: "invalid-input", phase: "input", message: "Input validation failed.", ...context },
      2,
      { cause },
    );
  }
  if (validated.issues)
    throw new CliError(
      {
        code: "invalid-input",
        phase: "input",
        message: "Input does not satisfy the shared service schema.",
        ...context,
        details: {
          paths: validated.issues.map((issue) =>
            (issue.path ?? []).map((segment) =>
              String(typeof segment === "object" ? segment.key : segment),
            ),
          ),
        },
      },
      2,
    );
  let running;
  try {
    running = await startApp(app);
  } catch (cause) {
    throw new CliError(diagnostic(cause, { ...context, phase: "setup" }), 1);
  }
  let result: unknown;
  let callFailed = false;
  let callError: unknown;
  try {
    const service = running.get(plugin);
    if (
      service === null ||
      typeof service !== "object" ||
      !Object.hasOwn(service, method) ||
      typeof Reflect.get(service, method) !== "function"
    ) {
      throw new CliError({
        code: "unavailable-operation",
        phase: "invoke",
        message: "Declared operation is not an own callable service method.",
        ...context,
      });
    }
    result = await Reflect.get(service, method).call(service, validated.value);
  } catch (cause) {
    callFailed = true;
    callError =
      cause instanceof CliError
        ? cause
        : new CliError(
            {
              code: "invocation-failed",
              phase: "invoke",
              message: "Service invocation failed.",
              ...context,
            },
            1,
            { cause },
          );
  }
  try {
    await running.stop();
  } catch (cleanupError) {
    if (callFailed)
      throw new CliError({
        code: "invocation-and-cleanup-failed",
        phase: "invoke",
        message: "Service invocation and cleanup failed.",
        ...context,
        causes: [
          diagnostic(callError, context),
          diagnostic(cleanupError, { ...context, phase: "cleanup" }),
        ],
      });
    throw new CliError(diagnostic(cleanupError, { ...context, phase: "cleanup" }));
  }
  if (callFailed) throw callError;
  return result;
}

export async function call(
  root: string,
  pluginId: string,
  method: string,
  input: unknown,
): Promise<unknown> {
  const { app } = await discover(root);
  try {
    return await invoke(app, pluginId, method, input);
  } catch (cause) {
    throw new CliError(
      diagnostic(cause, { source: { file: join(resolve(root), "lenso.config.ts") } }),
      cause instanceof CliError ? cause.exitCode : 1,
    );
  }
}

/** Imports trusted config but never runs setup or discovers methods by reflection. */
export async function inspect(root = process.cwd(), pluginId?: string, method?: string) {
  const { app, ordered, configPath } = await discover(root);
  if (pluginId && !ordered.some((plugin) => plugin.id === pluginId))
    throw new CliError(
      {
        code: "unknown-plugin",
        phase: "discovery",
        message: "Unknown plugin.",
        pluginId,
        source: { file: configPath },
      },
      3,
    );
  const operations = (app.operations ?? []).filter(
    (operation) =>
      (!pluginId || operation.plugin.id === pluginId) && (!method || operation.method === method),
  );
  if (method && !operations.length)
    throw new CliError(
      {
        code: "unknown-operation",
        phase: "discovery",
        message: "Operation is not declared.",
        source: { file: configPath },
      },
      3,
    );
  return {
    configPath,
    plugins: ordered.map((plugin) => ({
      id: plugin.id,
      requires: (plugin.requires ?? []).map((dependency) => dependency.id),
      source: { file: configPath },
    })),
    operations: operations.map((operation) => describeOperation(operation, configPath)),
    limitations: [
      "Imports trusted config and executes module top-level code.",
      "Never runs plugin setup; runtime-only methods and authorization outcomes cannot be discovered.",
      "Each call starts and stops an isolated app; no automatic retry, cancellation or request drain.",
    ],
  };
}
