import { mkdir, access } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { startApp, validatePlugins, type Contribution, type Plugin } from 'lenso';

export interface AppDefinition { readonly plugins: readonly Plugin<unknown>[] }
export interface PluginManifest {
  readonly id: string;
  readonly requires: readonly string[];
  readonly contributions: readonly Contribution[];
}
export interface Discovery {
  readonly root: string;
  readonly configPath: string;
  readonly app: AppDefinition;
  readonly ordered: readonly Plugin<unknown>[];
}

export async function discover(root = process.cwd()): Promise<Discovery> {
  const directory = resolve(root);
  const configPath = join(directory, 'lenso.config.ts');
  await access(configPath);
  const loaded = await import(pathToFileURL(configPath).href);
  const app: unknown = loaded.default;
  if (!app || typeof app !== 'object' || !('plugins' in app) || !Array.isArray(app.plugins)) {
    throw new Error('lenso.config.ts must default-export defineApp({ plugins: [...] })');
  }
  const definition = app as AppDefinition;
  return { root: directory, configPath, app: definition, ordered: validatePlugins(definition.plugins) };
}

function sourceImport(fromDirectory: string, target: string): string {
  const path = relative(fromDirectory, target).replaceAll('\\', '/').replace(/\.(?:tsx?|jsx?)$/, '');
  return path.startsWith('.') ? path : `./${path}`;
}

async function writeGenerated(path: string, content: string): Promise<void> {
  const existing = Bun.file(path);
  if (await existing.exists() && await existing.text() === content) return;
  await Bun.write(path, content);
}

/** Discovers and writes static imports only. Plugin setup never runs at build time. */
export async function generate(root = process.cwd()): Promise<readonly PluginManifest[]> {
  const discovery = await discover(root);
  const directory = join(discovery.root, '.lenso');
  const manifest: readonly PluginManifest[] = discovery.ordered.map(plugin => ({
    id: plugin.id,
    requires: (plugin.requires ?? []).map(dependency => dependency.id),
    contributions: plugin.contributions ?? [],
  }));
  await mkdir(directory, { recursive: true });
  const header = '// Generated by lenso-cli; run lenso generate after changing assembly.\n';
  await writeGenerated(join(directory, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  await writeGenerated(join(directory, 'server.ts'), `${header}export { default as app } from ${JSON.stringify(sourceImport(directory, discovery.configPath))};\n`);
  const routerPath = join(discovery.root, 'src/router.ts');
  if (await Bun.file(routerPath).exists()) {
    await writeGenerated(join(directory, 'client.ts'), `${header}import { createClient as createWebClient } from '@lenso/web/client';\nimport type { AppRouter } from ${JSON.stringify(sourceImport(directory, routerPath))};\nexport type { AppRouter };\nexport const createClient = (url: string) => createWebClient<AppRouter>(url);\n`);
  } else {
    // A stable empty browser entry prevents a removed Web integration leaving stale imports.
    await writeGenerated(join(directory, 'client.ts'), `${header}export {};\n`);
  }
  return manifest;
}

export async function build(root = process.cwd(), entry?: string): Promise<string> {
  await generate(root);
  const directory = resolve(root);
  const conventionalEntry = join(directory, 'src/server.ts');
  const entryPath = entry ? resolve(directory, entry) : await Bun.file(conventionalEntry).exists() ? conventionalEntry : join(directory, '.lenso/server.ts');
  const outdir = join(directory, 'dist');
  const result = await Bun.build({
    entrypoints: [entryPath], outdir, target: 'bun', sourcemap: 'external',
    packages: 'external',
  });
  if (!result.success) throw new AggregateError(result.logs, 'Application build failed');
  return outdir;
}

export async function invoke(app: AppDefinition, pluginId: string, method: string, input: unknown): Promise<unknown> {
  const plugin = app.plugins.find(candidate => candidate.id === pluginId);
  if (!plugin) throw new Error(`Unknown plugin: ${pluginId}`);
  const running = await startApp(app);
  try {
    const service = running.get(plugin);
    if (service === null || typeof service !== 'object' || !Object.hasOwn(service, method)) {
      throw new Error(`Plugin ${pluginId} does not expose method ${method}`);
    }
    const callable: unknown = Reflect.get(service, method);
    if (typeof callable !== 'function') throw new Error(`Plugin ${pluginId}.${method} is not callable`);
    return await callable.call(service, input);
  } finally {
    await running.stop();
  }
}

export async function call(root: string, pluginId: string, method: string, input: unknown): Promise<unknown> {
  const { app } = await discover(root);
  return invoke(app, pluginId, method, input);
}
