import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { pathToFileURL } from "node:url";
import vm from "node:vm";

const asset = fs.readFileSync(new URL("../assets/plugin-build.mjs", import.meta.url), "utf8");
// Evaluate the production classifier without starting package extraction or Bun.build.
const classifier = asset.slice(asset.indexOf("const packageCache ="), asset.indexOf("const definition ="));

function fixture(t, { integrity = "sha512-selected", exported = true } = {}) {
  const temporary = fs.mkdtempSync(path.join(os.tmpdir(), "lenso-build-symbols-"));
  t.after(() => fs.rmSync(temporary, { recursive: true }));
  const root = fs.realpathSync(temporary);
  const directory = path.join(root, "node_modules/@lenso/bun-plugin");
  fs.mkdirSync(path.join(directory, "dist"), { recursive: true });
  fs.writeFileSync(path.join(directory, "package.json"), JSON.stringify({
    name: "@lenso/bun-plugin",
    version: "0.4.2",
    exports: exported ? {
      ".": { types: "./dist/index.d.ts", import: "./dist/index.js" },
      "./authoring": { types: "./dist/authoring.d.ts", import: "./dist/authoring.js" },
    } : {},
  }));
  const declaration = path.join(directory, "dist/authoring.d.ts");
  fs.writeFileSync(declaration, "export declare function configuration(): void;\n");
  const context = vm.createContext({
    fs, path, root, pathToFileURL,
    lock: { packages: { sdk: ["@lenso/bun-plugin@0.4.2", "", {}, integrity] } },
    digest: (source) => `sha256:${createHash("sha256").update(source).digest("hex")}`,
  });
  return {
    root, declaration,
    ...vm.runInContext(`${classifier}\n({ classifySymbol, lockedPackages, contractArtifacts, generatedProviderDescriptors });`, context),
  };
}

test("locked public SDK declarations do not require a generated runtime sidecar", (t) => {
  const value = fixture(t);
  assert.equal(fs.existsSync(value.declaration.replace(/\.d\.ts$/u, ".js")), false);
  for (const name of ["definePlugin", "configuration", "dependency", "provider"]) {
    const meaning = value.classifySymbol({ file: value.declaration, module: "@lenso/bun-plugin", name });
    assert.equal(meaning.kind, name === "definePlugin" ? "plugin_definition" : "declaration");
    if (name !== "definePlugin") {
      assert.equal(meaning.package.integrity, "sha512-selected");
      assert.equal(meaning.export_name, name);
      assert.equal(JSON.stringify(meaning.handler_parameters), name === "dependency" ? undefined : "[1]");
    }
  }
  assert.equal(value.lockedPackages.size, 1);
  assert.equal(value.contractArtifacts.size, 0);
});

test("standard SDK names still require registry integrity and a public export", (t) => {
  for (const options of [{ integrity: null }, { exported: false }]) {
    const value = fixture(t, options);
    assert.throws(() => value.classifySymbol({
      file: value.declaration, module: "@lenso/bun-plugin", name: "configuration",
    }), options.exported === false ? /not a public package export/u : /registry integrity/u);
  }
});

test("pure authoring export uses the same locked source-first declaration contract", (t) => {
  const value = fixture(t);
  for (const name of ["definePlugin", "configuration", "dependency", "provider"]) {
    const meaning = value.classifySymbol({ file: value.declaration, module: "@lenso/bun-plugin/authoring", name });
    assert.equal(meaning.kind, name === "definePlugin" ? "plugin_definition" : "declaration");
    if (name !== "definePlugin") assert.equal(meaning.package.integrity, "sha512-selected");
  }
  assert.equal(value.contractArtifacts.size, 0);
});

test("a real generated contract still requires its runtime module", (t) => {
  const value = fixture(t);
  const declaration = path.join(value.root, "document-store.d.ts");
  fs.writeFileSync(declaration, "export declare const DOCUMENT_STORE_CONTRACT: unknown;\n");
  assert.throws(() => value.classifySymbol({ file: declaration, name: "DOCUMENT_STORE_CONTRACT" }), /no runtime module/u);
});

test("modern generated contracts retain full digest and operation evidence", (t) => {
  const value = fixture(t);
  const runtime = path.join(value.root, "document-store.js");
  const digest = `sha256:${"a".repeat(64)}`;
  fs.writeFileSync(runtime, [
    "/* @generated by lenso-contract-codegen; do not edit. */",
    'export const CAPABILITY_ID = "example.store@1";',
    'export const DESCRIPTOR_VERSION = "1.0.0";',
    `export const DESCRIPTOR_DIGEST = "${digest}";`,
    'export const DocumentStore = { kind: "lenso.capability", descriptor: { operations: ["read", "watch"], stream_operations: ["watch"], event_operations: [] } };',
  ].join("\n"));
  const meaning = value.classifySymbol({ file: runtime, name: "DocumentStore" });
  assert.equal(meaning.kind, "contract");
  assert.equal(meaning.descriptor_digest, digest);
  assert.equal(meaning.generated_module, pathToFileURL(runtime).href);
  const operations = value.generatedProviderDescriptors.get(`${meaning.generated_module}#DocumentStore`);
  assert.equal(JSON.stringify(operations), JSON.stringify({ request_operations: ["read"], stream_operations: ["watch"], event_operations: [] }));
  assert.equal(value.contractArtifacts.size, 1);
});

test("generated contract markers and required digest are still enforced", (t) => {
  const value = fixture(t);
  const runtime = path.join(value.root, "contract.js");
  const origin = { file: runtime, name: "STORE_CONTRACT" };
  fs.writeFileSync(runtime, 'export const STORE_CONTRACT = {};\n');
  assert.equal(value.classifySymbol(origin), undefined);
  fs.writeFileSync(runtime, [
    "/* @generated by lenso-contract-codegen; do not edit. */",
    'export const CAPABILITY_ID = "example.store@1";',
    'export const DESCRIPTOR_VERSION = "1.0.0";',
    'export const STORE_CONTRACT = {};',
  ].join("\n"));
  assert.throws(() => value.classifySymbol(origin), /missing DESCRIPTOR_DIGEST/u);
});
