import { createHash, randomUUID } from 'node:crypto';
import { mkdir, open, readFile, rename, rm } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';

const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'] as const;

export type GenerateClientOptions = {
  readonly input: string;
  readonly output: string;
};

export async function generateClientTypes(options: GenerateClientOptions): Promise<{ digest: string; operationCount: number }> {
  const input = resolve(options.input);
  const output = resolve(options.output);
  const source = await readFile(input);
  const document = parsePublicDocument(source, input);
  rejectExternalReferences(document);
  const operationCount = validatePublicDocument(document);
  const digest = createHash('sha256').update(source).digest('hex');
  const ast = await openapiTS(document, { alphabetize: true, pathParamsAsTypes: true });
  const generated = [
    '/**',
    ' * Generated from the caller-selected OpenAPI document.',
    ` * Source SHA-256: ${digest}`,
    ' * Do not edit this file directly.',
    ' */',
    '',
    astToString(ast).trimStart(),
  ].join('\n');

  await mkdir(dirname(output), { recursive: true });
  const temporary = `${output}.${process.pid}.${randomUUID()}.tmp`;
  let file;
  try {
    file = await open(temporary, 'wx');
    await file.writeFile(generated);
    await file.close();
    file = undefined;
    await rename(temporary, output);
  } catch (error) {
    await file?.close();
    await rm(temporary, { force: true });
    throw error;
  }
  return { digest, operationCount };
}

function rejectExternalReferences(value: unknown): void {
  if (Array.isArray(value)) {
    for (const item of value) rejectExternalReferences(item);
    return;
  }
  if (typeof value !== 'object' || value === null) return;
  for (const [key, child] of Object.entries(value)) {
    if (key === '$ref' && (typeof child !== 'string' || !child.startsWith('#/'))) {
      throw new Error('OpenAPI input must be self-contained; external $ref values are not allowed');
    }
    rejectExternalReferences(child);
  }
}

function parsePublicDocument(source: Buffer, input: string): OpenAPI3 {
  try {
    return JSON.parse(source.toString('utf8')) as OpenAPI3;
  } catch (error) {
    throw new Error(`Could not parse OpenAPI JSON at ${input}`, { cause: error });
  }
}

function validatePublicDocument(document: OpenAPI3): number {
  if (!/^3\.1(?:\.\d+)?$/.test(document.openapi)) throw new Error('Lenso browser clients require an OpenAPI 3.1.x document');
  if (document.webhooks !== undefined && Object.keys(document.webhooks).length > 0) {
    throw new Error('OpenAPI webhooks are not supported by the browser client generator');
  }
  let operations = 0;
  for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
    if ('$ref' in pathItem) throw new Error(`Path-level references are not supported for ${path}`);
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (operation === undefined) continue;
      if ('$ref' in operation) throw new Error(`Operation references are not supported for ${method.toUpperCase()} ${path}`);
      if (typeof operation.operationId !== 'string' || operation.operationId.length === 0) {
        throw new Error(`Public operation ${method.toUpperCase()} ${path} must have a stable operationId`);
      }
      operations += 1;
    }
  }
  if (operations === 0) throw new Error('The OpenAPI document does not expose any public operations');
  return operations;
}
